# Stamping, reporting, exporting and snapshots (test_hard_misc.py).

with_scelo_home <- function(dir, code) {
  old <- Sys.getenv("SCELO_HOME", unset = NA)
  Sys.setenv(SCELO_HOME = dir)
  on.exit(if (is.na(old)) Sys.unsetenv("SCELO_HOME") else Sys.setenv(SCELO_HOME = old), add = TRUE)
  force(code)
}

test_that("hard stamps and verify detects edits", {
  sc_clear_audit()
  r <- sc_wmtr(nPaths = 5, horizon = 3)
  t <- sc_hard(r$table, assumptions = list(i = 0.04))
  expect_s3_class(t, "scelo_table")
  expect_true(sc_verify(t))
  p <- sc_provenance(t)
  expect_identical(p$assumptions, list(i = 0.04))
  expect_identical(nchar(p$hash), 32L)
  expect_identical(p$hash, sc_content_hash(sc_df(r$table)))
  expect_identical(p$rows, 4L)
  expect_identical(p$columns, names(r$table))
  expect_identical(p$scelo, .sc_version())
  expect_match(p$at, "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\+00:00$")
  expect_match(p$r, "^[0-9]+\\.[0-9]+")
  expect_identical(attr(t, "stage"), "hard")
  expect_identical(p$trail[[length(p$trail)]]$fn, "sc_wmtr")
  expect_identical(names(p$trail[[1]]), c("fn", "at", "in", "out"))
  t$mean_W[1] <- 0.5
  expect_false(sc_verify(t))
  # an unstamped table has no provenance and cannot verify
  expect_identical(sc_provenance(data.frame(x = 1)), list())
  expect_false(sc_verify(data.frame(x = 1)))
  # a plain frame: title / basis / note / at most 12 trail entries
  for (i in 1:14) sc_wmtr(nPaths = 2, horizon = 1)
  h <- sc_hard(data.frame(x = 1:3), title = "three", basis = "toy", note = "a note")
  expect_identical(sc_title(h), "three")
  expect_identical(sc_basis(h), "toy")
  expect_identical(sc_notes(h), "a note")
  expect_length(sc_provenance(h)$trail, 12)
  expect_output(print(h), "hard · ")
  # stamping a stamped table with a new title keeps the table and re-hashes
  h2 <- sc_hard(h, title = "renamed")
  expect_identical(sc_title(h2), "renamed")
  expect_identical(sc_provenance(h2)$hash, sc_provenance(h)$hash)
})

test_that("report writes Markdown and HTML; export writes by extension", {
  dir <- tempfile("pack")
  dir.create(dir)
  sc_clear_audit()
  r <- sc_wmtr(nPaths = 5, horizon = 3)
  md <- sc_report(r$table, "## Note\n\ntext", title = "Pack", summary = "ok", to = file.path(dir, "pack.md"))
  expect_true(file.exists(file.path(dir, "pack.md")))
  expect_match(md, "^# Pack\n")
  expect_match(md, "## Executive summary\n\nok\n", fixed = TRUE)
  expect_match(md, "### WMTR forecast · moderate shocks · 3y · 5 paths · seed 42", fixed = TRUE)
  expect_match(md, "## Audit trail")
  expect_match(md, "| sc_wmtr |", fixed = TRUE)
  expect_match(md, "## Note\n\ntext", fixed = TRUE)
  expect_match(md, "<sub>hard · ")
  expect_match(md, "<sub>scelo · soft data → tools → hard data", fixed = TRUE)
  expect_identical(readLines(file.path(dir, "pack.md"), encoding = "UTF-8"), strsplit(md, "\n", fixed = TRUE)[[1]])
  # a visible return without `to`, and an author line
  md2 <- sc_report(r, author = "AD")
  expect_match(md2, "· scelo [0-9.]+ · AD\\*")
  expect_match(md2, "# Board pack")
  # plain data frames get numbered titles and are stamped unless asked not to
  md3 <- sc_report(data.frame(x = 1:2), data.frame(y = 3), stamp = FALSE)
  expect_match(md3, "### Table 1")
  expect_match(md3, "### Table 2")
  expect_false(grepl("<sub>hard", md3))
  expect_match(sc_report(data.frame(x = 1:2)), "<sub>hard · ")
  # HTML
  sc_report(r$table, "## Note\n\ntext", to = file.path(dir, "pack.html"))
  html <- paste(readLines(file.path(dir, "pack.html"), encoding = "UTF-8"), collapse = "\n")
  expect_match(html, "^<!doctype html>")
  expect_match(html, "<table>", fixed = TRUE)
  expect_match(html, "<h1>Board pack</h1>", fixed = TRUE)
  expect_match(html, "<h2>Note</h2>", fixed = TRUE)
  expect_match(html, "<th>year</th>", fixed = TRUE)
  expect_match(html, "<li>Outcomes: grew", fixed = TRUE)
  expect_match(html, "<hr>", fixed = TRUE)
  expect_match(html, "<p><sub>scelo · soft data", fixed = TRUE)
  expect_false(grepl("|---|", html, fixed = TRUE))
  expect_false(file.exists(file.path(dir, "pack.html.partial")))
  # export by extension
  p <- sc_export(r$table, file.path(dir, "t.csv"))
  expect_true(file.exists(p))
  expect_identical(nrow(sc_load(p)), 4L)
  sc_export(r$table, file.path(dir, "t.md"))
  expect_match(paste(readLines(file.path(dir, "t.md"), encoding = "UTF-8"), collapse = "\n"), "WMTR forecast", fixed = TRUE)
  sc_export(r$table, file.path(dir, "t.html"))
  expect_match(paste(readLines(file.path(dir, "t.html"), encoding = "UTF-8"), collapse = "\n"), "<table>", fixed = TRUE)
  expect_error(sc_report(42), "takes tables, data frames and strings")
})

test_that("the Markdown to HTML converter handles code, tables, escaping", {
  md <- c("# T & co", "", "```", "a < b", "```", "| a | b |", "|---|---|", "| 1 | x<y |", "", "- item", "plain \"quoted\"", "---", "<sub>foot</sub>")
  html <- .sc_md_to_html(paste(md, collapse = "\n"))
  expect_match(html, "<h1>T &amp; co</h1>", fixed = TRUE)
  expect_match(html, "<pre>\na &lt; b\n</pre>", fixed = TRUE)
  expect_match(html, "<tr><th>a</th><th>b</th></tr>", fixed = TRUE)
  expect_match(html, "<tr><td>1</td><td>x&lt;y</td></tr>\n</table>", fixed = TRUE)
  expect_match(html, "<li>item</li>", fixed = TRUE)
  expect_match(html, "<p>plain &quot;quoted&quot;</p>", fixed = TRUE)
  expect_match(html, "<p><sub>foot</sub></p>", fixed = TRUE)
})

test_that("snapshot, restore and the listing", {
  home <- tempfile("scelo-home")
  with_scelo_home(home, {
    df <- sc_sample("claims")
    p <- sc_snapshot(df, "claims0")
    expect_true(file.exists(p))
    expect_identical(basename(p), "claims0.rds")
    back <- sc_restore("claims0")
    expect_identical(dim(back), dim(df))
    expect_identical(back$paid, df$paid)
    s <- sc_snapshots()
    expect_identical(names(s), c("name", "at", "rows", "cols", "hash"))
    expect_true("claims0" %in% s$name)
    expect_identical(s$rows[s$name == "claims0"], 79)
    expect_identical(s$hash[s$name == "claims0"], sc_content_hash(as.data.frame(df)))
    expect_error(sc_restore("nope"), "no snapshot named 'nope'")
    # a sidecar written by the Python package (sha256 key, CSV payload) is listed and restored
    d <- file.path(home, "snapshots")
    utils::write.csv(data.frame(a = 1:2, b = c("x", "y")), file.path(d, "py1.csv"), row.names = FALSE)
    writeLines(c("{", "  \"name\": \"py1\",", "  \"at\": \"2026-08-23T10:00:00+00:00\",", "  \"rows\": 2,", "  \"cols\": 2,", "  \"sha256\": \"ab\\\"cd\"", "}"), file.path(d, "py1.json"))
    s2 <- sc_snapshots()
    expect_identical(s2$name, c("claims0", "py1"))
    expect_identical(s2$hash[2], "ab\"cd")
    expect_identical(s2$rows[2], 2)
    expect_identical(sc_restore("py1")$b, c("x", "y"))
  })
  with_scelo_home(tempfile("empty-home"), expect_identical(nrow(sc_snapshots()), 0L))
})
