# Combine: the cases of packages/scelo-py/tests/test_hard_misc.py::test_combine_rules
# and the golden combine blocks computed by the Python package.

combine_frames <- function() {
  list(
    a = data.frame(policy_id = c("P1", "P2", "P3"), premium = c(1L, 2L, 3L), stringsAsFactors = FALSE),
    b = data.frame(Policy_ID = c("P1", "P2", "P2", "P4"), claims = 0:3, premium = c(9L, 9L, 9L, 9L), stringsAsFactors = FALSE)
  )
}

test_that("suggest_combine reproduces the Python golden", {
  f <- combine_frames()
  s <- sc_suggest_combine(f$a, f$b)
  expect_s3_class(s, "scelo_table")
  want <- split_df(golden()$combine$suggest)
  expect_equal(names(s), names(want))
  expect_equal(s$strategy, want$strategy)
  expect_equal(s$key, want$key)
  expect_equal(s$right_key, want$right_key)
  expect_close(s$confidence, want$confidence)
  expect_equal(s$dedupe_exact, as.logical(want$dedupe_exact))
  expect_close(s$schema_overlap, want$schema_overlap)
  expect_equal(s$shared_columns, as.integer(want$shared_columns))
  expect_equal(s$candidate_keys, want$candidate_keys)
  keys <- attr(s, "keys")
  expect_equal(length(keys), 1L)
  expect_equal(keys[[1]]$key, "policy_id")
  expect_close(keys[[1]]$score, 2 / 3 + 0.15)
  expect_equal(sc_title(s), "Combine suggestion")
  # schemas that line up: append, with exact-duplicate removal
  s2 <- sc_suggest_combine(f$a, f$a)
  expect_equal(s2$strategy, "append")
  expect_true(s2$dedupe_exact)
  expect_equal(s2$confidence, 0.6) # a key with full overlap lowers the confidence in an append
  s3 <- sc_suggest_combine(f$a, data.frame(policy_id = c("Q1", "Q2", "Q3"), premium = 1:3, stringsAsFactors = FALSE))
  expect_equal(s3$confidence, 0.6) # premium is a fully overlapping unique column, so it reads as a key
  expect_equal(s3$candidate_keys, "premium")
  s3b <- sc_suggest_combine(f$a, data.frame(policy_id = c("Q1", "Q2", "Q3"), premium = 10:12, stringsAsFactors = FALSE))
  expect_equal(s3b$confidence, 0.9)
  expect_equal(s3b$candidate_keys, "")
  s4 <- sc_suggest_combine(f$a, data.frame(x = 1:3, y = 4:6))
  expect_equal(s4$strategy, "append")
  expect_equal(s4$confidence, 0.25)
  expect_true(is.na(s4$key))
})

test_that("join: first right match wins, clashes renamed, golden frame", {
  f <- combine_frames()
  j <- sc_join(f$a, f$b)
  expect_s3_class(j, "scelo_table")
  want <- split_df(golden()$combine$join)
  expect_equal(names(j), names(want))
  expect_equal(nrow(j), 3L)
  expect_equal(j$policy_id, want$policy_id)
  expect_equal(as.numeric(j$premium), want$premium)
  expect_equal(as.numeric(j$claims), want$claims)
  expect_equal(as.numeric(j$premium_2), want$premium_2)
  expect_equal(j$premium_2[1:2], c(9L, 9L))
  expect_equal(j$claims[1:2], c(0L, 1L)) # first right match wins
  expect_true(is.na(j$claims[3]))
  expect_equal(sc_notes(j), "2 of 3 base rows matched; 1 unmatched kept with nulls; 1 duplicate right keys ignored (first wins). Renamed: premium→premium_2.")
  expect_equal(sc_title(j), "left join on policy_id")
  inner <- sc_join(f$a, f$b, how = "inner")
  expect_equal(nrow(inner), 2L)
  expect_equal(sc_notes(inner), "2 of 3 base rows matched; 1 unmatched dropped; 1 duplicate right keys ignored (first wins). Renamed: premium→premium_2.")
  explicit <- sc_join(f$a, f$b, key = "policy_id", right_key = "Policy_ID")
  expect_equal(sc_df(explicit), sc_df(j))
  expect_error(sc_join(f$a, data.frame(x = 1:3)), "no shared key column: pass key=<column>")
  expect_error(sc_join(f$a, f$b, key = "nope"), "key nope not in base dataset")
  expect_error(sc_join(f$a, f$b, key = "policy_id", right_key = "nope"), "key nope not in second dataset")
  # a right frame with only the key adds nothing but still matches
  only_key <- sc_join(f$a, data.frame(policy_id = c("P3", "P1")))
  expect_equal(names(only_key), c("policy_id", "premium"))
  expect_equal(sc_notes(only_key), "2 of 3 base rows matched; 1 unmatched kept with nulls; 0 duplicate right keys ignored (first wins).")
})

test_that("append and combine", {
  f <- combine_frames()
  a2 <- f$a
  a2$premium <- c(1L, 2L, 5L)
  ap <- sc_append(f$a, a2)
  expect_s3_class(ap, "scelo_table")
  want <- split_df(golden()$combine$append)
  expect_equal(nrow(ap), 4L)
  expect_equal(ap$policy_id, want$policy_id)
  expect_equal(as.numeric(ap$premium), want$premium)
  expect_equal(sc_notes(ap), "3 rows appended; 0 new column(s); 2 exact duplicates dropped.")
  expect_equal(nrow(sc_append(f$a, a2, dedupe = FALSE)), 6L)
  expect_equal(sc_notes(sc_append(f$a, a2, dedupe = FALSE)), "3 rows appended; 0 new column(s).")
  expect_identical(sc_stack, sc_append)
  wide <- sc_append(f$a, data.frame(Policy_ID = "P9", region = "x", stringsAsFactors = FALSE))
  expect_equal(names(wide), c("policy_id", "premium", "region")) # columns matched case-insensitively, union kept
  expect_equal(wide$policy_id, c("P1", "P2", "P3", "P9"))
  expect_true(is.na(wide$premium[4]) && is.na(wide$region[1]))
  dated <- sc_append(data.frame(d = as.Date("2024-01-01")), data.frame(D = as.Date("2024-02-01")))
  expect_s3_class(dated$d, "Date")
  c <- sc_combine(f$a, a2)
  expect_equal(nrow(c), 4L)
  expect_equal(sc_notes(c), c("append (confidence 0.60)", "3 rows appended; 0 new column(s); 2 exact duplicates dropped."))
  expect_equal(sc_title(c), "combine · 2 datasets")
  cj <- sc_combine(f$a, f$b)
  expect_equal(names(cj), c("policy_id", "premium", "claims", "premium_2"))
  expect_equal(sc_notes(cj)[1], "join-left (confidence 0.82)")
  forced <- sc_combine(f$a, f$b, how = "inner", key = "policy_id")
  expect_equal(nrow(forced), 2L)
  expect_equal(nrow(sc_combine(f$a, a2, how = "append")), 4L)
  three <- sc_combine(f$a, a2, f$b) # after the append policy_id is only 75 % unique, so the third frame appends too
  expect_equal(nrow(three), 8L)
  expect_true("claims" %in% names(three))
  expect_equal(sc_title(three), "combine · 3 datasets")
  expect_equal(sc_notes(three), c("append (confidence 0.60)", "3 rows appended; 0 new column(s); 2 exact duplicates dropped.", "append (confidence 0.50)", "4 rows appended; 1 new column(s)."))
})

test_that("diff and tieout", {
  f <- combine_frames()
  a2 <- f$a
  a2$premium <- c(1L, 2L, 5L)
  d <- sc_diff(f$a, a2, key = "policy_id")
  expect_s3_class(d, "scelo_table")
  expect_equal(nrow(d), 1L)
  expect_equal(d$delta[1], -2)
  expect_equal(d$key, "P3")
  expect_equal(d$column, "premium")
  expect_equal(sc_notes(d), "3 aligned rows; rows only in a: 0, only in b: 0; columns only in a: none, only in b: none.")
  expect_equal(sc_title(d), "diff · 1 differing cells")
  pos <- sc_diff(f$a, a2)
  expect_equal(pos$key, 3L) # positional alignment: the row number
  expect_equal(nrow(sc_diff(f$a, a2, key = "policy_id", tol = 2)), 0L)
  b2 <- data.frame(policy_id = c("P1", "P2", "P9"), premium = c(1L, NA, 3L), extra = 1, stringsAsFactors = FALSE)
  d2 <- sc_diff(f$a, b2, key = "policy_id")
  expect_equal(d2$key, "P2") # NA against a value is a difference
  expect_equal(sc_notes(d2), "2 aligned rows; rows only in a: 1, only in b: 1; columns only in a: none, only in b: extra.")
  txt <- sc_diff(data.frame(k = 1:2, s = c("a", NA), stringsAsFactors = FALSE), data.frame(k = 1:2, s = c("b", NA), stringsAsFactors = FALSE), key = "k")
  expect_equal(nrow(txt), 1L)
  expect_true(is.na(txt$delta))
  expect_true(sc_tieout(1.0, 1.0 + 1e-9))
  expect_false(sc_tieout(f$a, a2))
  expect_true(sc_tieout(f$a, f$a))
  expect_false(sc_tieout(f$a, f$b))
  expect_true(sc_tieout(100, 100.5, tol = 0.01, rel = TRUE))
  expect_false(sc_tieout(100, 100.5, tol = 0.001, rel = TRUE))
  expect_true(sc_tieout(c(1, 2, 3), c(1, 2, 3 + 1e-9)))
  expect_false(sc_tieout(c(1, 2), c(1, 2, 3)))
  expect_true(sc_tieout(data.frame(x = c("a", NA)), data.frame(x = c("a", NA))))
})
