# Reserving: the RAA triangle (Mack 1993) against the published values the
# Python package reproduces, plus the claims-sample triangle cell by cell.

raa_triangle <- function() sc_from_wide(golden()$raa$triangle, origins = 1981:1990)

# golden reserve tables carry origin as a column; compare every numeric column
expect_table_close <- function(got, want, tol = 1e-6) {
  expect_equal(names(got), names(want))
  expect_equal(as.character(got$origin), as.character(want$origin))
  for (c in setdiff(names(want), "origin")) expect_close(got[[c]], want[[c]], tol, label = c)
}

test_that("RAA triangle wraps as a cumulative scelo triangle", {
  raa <- raa_triangle()
  expect_s3_class(raa, "scelo_table")
  expect_true(attr(raa, "scelo_triangle"))
  expect_true(sc_is_cumulative(raa))
  expect_equal(dim(raa), c(10, 10))
  expect_equal(rownames(raa), as.character(1981:1990))
  expect_equal(names(raa), as.character(0:9))
  expect_equal(raa[["0"]][1], 5012)
  expect_true(is.na(raa[["9"]][2]))
  expect_equal(attr(raa, "title"), "Cumulative triangle")
})

test_that("Mack on RAA reproduces the published values", {
  g <- golden()$raa
  raa <- raa_triangle()
  m <- sc_mack(raa)
  expect_s3_class(m, "scelo_reserving")
  expect_equal(m$method, "mack")
  expect_equal(round(m$ibnr), 52135)
  expect_equal(round(m$ultimate), 213122)
  expect_equal(round(m$latest), 160987)
  expect_equal(round(m$se), 26909)  # Mack (1993), R ChainLadder est.sigma = "Mack"
  expect_lt(abs(m$cv - 0.52), 0.01)
  se <- round(m$table$se[m$table$origin != "total"])
  expect_equal(se, c(0, 206, 623, 747, 1469, 2002, 2209, 5358, 6333, 24566))
  expect_close(m$factors, g$factors, 1e-10, "factors")
  expect_close(m$cdf, g$cdf, 1e-10, "cdf")
  expect_close(m$detail$sigma2, g$sigma2, 1e-10, "sigma2")
  expect_table_close(sc_df(m$table), split_df(g$mack), 1e-8)
  expect_equal(attr(m$table, "title"), "Mack chain ladder")
  expect_equal(attr(m$table, "basis"), "volume-weighted link ratios · Mack (1993) MSE")
  expect_match(sc_notes(m$table)[1], "^SE is the square root of Mack's MSE")
})

test_that("chain ladder on RAA: factors, cdf, ldf tail", {
  raa <- raa_triangle()
  cl <- sc_chain_ladder(raa)
  expect_equal(cl$method, "chain-ladder")
  expect_close(cl$factors[1:3], c(2.999, 1.624, 1.271), 1e-3, "first factors")
  expect_equal(round(cl$ibnr), 52135)
  expect_lt(abs(sc_cdf(raa)[[1]] - prod(cl$factors)), 1e-9)
  ldf <- sc_ldf(raa)
  expect_equal(names(ldf)[length(ldf)], "tail")
  expect_equal(names(ldf)[1], "0→1")
  expect_equal(names(sc_cdf(raa)), as.character(0:9))
  expect_equal(cl$table$origin, c(as.character(1981:1990), "total"))
  expect_equal(names(cl$table), c("origin", "latest", "cdf", "pct_developed", "ultimate", "ibnr"))
  expect_true(is.na(cl$table$cdf[11]))
  expect_equal(cl$table$ibnr[11], cl$ibnr)
  expect_equal(attr(cl$table, "basis"), "volume-weighted link ratios")
  cl2 <- sc_chain_ladder(raa, average = "simple", n_periods = 3, tail_factor = 1.05)
  expect_equal(attr(cl2$table, "basis"), "simple-weighted link ratios · last 3 · tail 1.05")
  expect_gt(cl2$ibnr, 0)
  expect_equal(unname(sc_ldf(raa, tail_factor = 1.05)[["tail"]]), 1.05)
  expect_equal(sc_latest_diagonal(raa), stats::setNames(c(18834, 16704, 23466, 27067, 26180, 15852, 12314, 13112, 5395, 2063), 1981:1990))
})

test_that("age-to-age factor table", {
  raa <- raa_triangle()
  a <- sc_ata(raa)
  expect_s3_class(a, "scelo_table")
  expect_equal(dim(a), c(12, 9))
  expect_equal(names(a), paste0(0:8, "→", 1:9))
  expect_equal(rownames(a), c(as.character(1981:1990), "volume-weighted", "simple average"))
  expect_close(a["1981", "0→1"], 8269 / 5012, 1e-12)
  expect_close(a["volume-weighted", "0→1"], golden()$raa$factors[1], 1e-10)
  expect_true(is.na(a["1990", "0→1"]))
})

test_that("Bornhuetter-Ferguson and Cape Cod", {
  g <- golden()$raa
  raa <- raa_triangle()
  cl <- sc_chain_ladder(raa)
  b <- sc_bf(raa, apriori = cl)
  expect_equal(b$method, "bornhuetter-ferguson")
  expect_lt(abs(b$ibnr - cl$ibnr), 1e-6)  # BF seeded with CL ultimates returns the CL reserve
  expect_equal(attr(b$table, "basis"), "a-priori: chain-ladder ultimates")
  b2 <- sc_bf(raa, apriori = 10000)  # a prior below every chain-ladder ultimate lowers the reserve
  expect_lt(b2$ibnr, b$ibnr)
  expect_table_close(sc_df(b2$table), split_df(g$bf_apriori_10000), 1e-8)
  expect_equal(attr(b2$table, "title"), "Bornhuetter–Ferguson")
  expect_equal(attr(b2$table, "basis"), "a-priori: given a-priori")
  b3 <- sc_bf(raa, apriori = 40000)
  expect_gt(b3$ibnr, b$ibnr)
  b4 <- sc_bf(raa, premium = rep(40000, 10), elr = 0.6)
  expect_equal(attr(b4$table, "basis"), "a-priori: premium × ELR 60.00%")
  expect_close(b4$table$apriori[1:10], rep(24000, 10), 1e-12)
  b5 <- sc_bf(raa)
  expect_equal(b5$detail$apriori_source, "book-average chain-ladder ultimate")
  expect_error(sc_bf(raa, apriori = c(1, 2, 3)), "one value per origin")
  cc <- sc_cape_cod(raa, premium = rep(40000, 10))
  expect_equal(cc$method, "cape-cod")
  expect_true(cc$detail$elr > 0 && cc$detail$elr < 2 && cc$ibnr > 0)
  expect_close(cc$detail$elr, g$cape_cod_40000$elr, 1e-10, "elr")
  expect_close(cc$ibnr, g$cape_cod_40000$ibnr, 1e-8, "cape cod ibnr")
  expect_equal(attr(cc$table, "basis"), sprintf("ELR %.2f%% from used-up premium", 100 * cc$detail$elr))
  expect_equal(names(cc$table), c("origin", "latest", "cdf", "pct_developed", "ultimate", "ibnr", "premium", "used_premium"))
})

test_that("ODP bootstrap on RAA: England & Verrall distribution, seeded", {
  raa <- raa_triangle()
  b <- sc_bootstrap(raa, n = 1000, seed = 42)
  expect_equal(b$method, "bootstrap")
  expect_true(b$ibnr > 50000 && b$ibnr < 57000)
  expect_true(b$se > 15000 && b$se < 22000)
  expect_true(b$detail$p95 > b$detail$p50 && b$detail$p50 > 0)
  expect_length(b$detail$totals, 1000)
  expect_equal(dim(b$detail$by_origin), c(1000, 10))
  expect_close(b$detail$phi, 983.6, 1e-3, "phi")
  expect_equal(b$table$se[11], b$se)
  expect_equal(attr(b$table, "title"), "ODP bootstrap · 1,000 simulations")
  expect_match(attr(b$table, "basis"), "^φ = 983\\.6 · gamma process error$")
  expect_match(sc_notes(b$table)[1], "^Total reserve p5 [0-9,]+ · p50 [0-9,]+ · p75 [0-9,]+ · p95 [0-9,]+ · p99 [0-9,]+\\.$")
  b2 <- sc_bootstrap(raa, n = 1000, seed = 42)
  expect_equal(b2$ibnr, b$ibnr)  # seeded
  expect_equal(b2$detail$totals, b$detail$totals)
  b3 <- sc_bootstrap(raa, n = 200, seed = 7, process = FALSE)
  expect_match(attr(b3$table, "basis"), "estimation error only$")
  expect_true(b3$ibnr > 40000 && b3$ibnr < 65000)
})

test_that("a seeded bootstrap leaves the session RNG where it was", {
  raa <- raa_triangle()
  set.seed(123)
  before <- runif(1)
  set.seed(123)
  sc_bootstrap(raa, n = 50, seed = 42)
  expect_equal(runif(1), before)
})

test_that("triangle from the long claims file matches the Python triangle", {
  g <- golden()
  claims <- sc_sample("claims")
  tri <- sc_triangle(claims)
  expect_s3_class(tri, "scelo_table")
  expect_equal(dim(tri), c(7, 7))
  expect_true(attr(tri, "scelo_triangle"))
  expect_true(is.na(tri[7, 2]) && !is.na(tri[1, 7]))  # future cells blank, diagonal filled
  expect_true(sc_is_cumulative(tri))
  expect_false(sc_is_cumulative(sc_to_incremental(tri)))
  expect_equal(as.matrix(sc_df(sc_to_cumulative(sc_to_incremental(tri)))), as.matrix(sc_df(tri)))
  inc <- sc_triangle(claims, cumulative = FALSE)
  expect_false(sc_is_cumulative(inc))
  expect_equal(as.matrix(sc_df(sc_to_cumulative(inc))), as.matrix(sc_df(tri)))
  want <- split_df(g$claims_triangle)
  expect_equal(rownames(tri), as.character(want$origin))
  expect_equal(names(tri), setdiff(names(want), "origin"))
  for (c in names(tri)) expect_close(tri[[c]], want[[c]], 1e-9, paste("lag", c))
  want_inc <- split_df(g$claims_triangle_inc)
  for (c in names(inc)) expect_close(inc[[c]], want_inc[[c]], 1e-9, paste("inc lag", c))
  expect_equal(attr(tri, "title"), "Cumulative triangle · paid by origin_year × development")
  expect_equal(attr(inc, "title"), "Incremental triangle · paid by origin_year × development")
  expect_equal(attr(tri, "basis"), "paid · origin_year × dev")
  expect_equal(sc_notes(tri), c("7 origin periods × 7 development lags, summed from 79 rows. Input rows treated as incremental amounts.", "Development lag read from `dev_period`."))
  expect_identical(sc_triangle(tri), tri)  # already a triangle
  expect_identical(sc_to_cumulative(tri), tri)
  expect_identical(sc_to_incremental(inc), inc)
})

test_that("triangle from a payment period", {
  df <- data.frame(accident_year = c(2020, 2020, 2021, 2021, 2022), calendar_year = c(2020, 2021, 2021, 2022, 2022), paid = c(100, 50, 120, 60, 130))
  tri <- sc_triangle(df, payment = "calendar_year")
  expect_equal(tri["2020", "1"], 150)
  expect_true(is.na(tri["2022", "1"]))
  expect_equal(tri["2021", "0"], 120)
  expect_equal(sc_notes(tri)[2], "Development lag = calendar_year − accident_year.")
  expect_error(sc_triangle(data.frame(accident_year = 2020, paid = 1)), "need a development-lag column")
})

test_that("triangle construction: cumulative input, skipped rows, zeros inside the diagonal", {
  df <- data.frame(origin = c(2019, 2019, 2019, 2020, 2020, 2021, "x"), dev = c(0, 1, 2, 0, 1, 0, 0), paid = c(100, 150, 175, 110, 160, 120, 5))
  tri <- sc_triangle(df, incremental_input = FALSE)
  expect_equal(tri["2019", "2"], 175)
  expect_match(sc_notes(tri)[1], "1 rows skipped")
  expect_match(sc_notes(tri)[1], "treated as cumulative amounts")
  inc <- sc_triangle(df, incremental_input = FALSE, cumulative = FALSE)
  expect_equal(unname(unlist(inc["2019", ])), c(100, 50, 25))
  gap <- data.frame(origin = c(2019, 2019, 2020), dev = c(0, 2, 0), paid = c(100, 20, 50))
  t2 <- sc_triangle(gap)
  expect_equal(unname(unlist(t2["2019", ])), c(100, 100, 120))  # no claims at lag 1 → 0 inside the observed region
  expect_equal(t2["2020", "1"], 50)  # 2020 + 1 is on the latest diagonal (2021): filled with 0, cumulated
  expect_true(is.na(t2["2020", "2"]))  # 2020 + 2 is beyond it
  expect_error(sc_triangle(data.frame(origin = "x", dev = 0, paid = 1)), "no \\(origin, development, value\\) triples")
  dates <- data.frame(origin = as.Date(c("2019-03-01", "2020-07-01")), dev = c(0, 0), paid = c(1, 2))
  expect_equal(rownames(sc_triangle(dates)), c("2019", "2020"))
  strings <- data.frame(origin = c("2019-Q1", "2020-Q1"), dev = c(0, 0), paid = c(1, 2))
  expect_equal(rownames(sc_triangle(strings)), c("2019", "2020"))
})

test_that("from_wide accepts matrices, lists and data frames", {
  m <- rbind(c(100, 150, 175), c(110, 160, NA), c(120, NA, NA))
  t1 <- sc_from_wide(m)
  expect_equal(rownames(t1), c("0", "1", "2"))
  expect_equal(names(t1), c("0", "1", "2"))
  t2 <- sc_from_wide(list(c(100, 150, 175), c(110, 160, NA), c(120, NA, NA)), origins = 2019:2021, cumulative = FALSE)
  expect_equal(rownames(t2), c("2019", "2020", "2021"))
  expect_false(sc_is_cumulative(t2))
  expect_equal(attr(t2, "title"), "Incremental triangle")
  d <- data.frame(origin = 2019:2021, `dev 0` = m[, 1], `dev 1` = m[, 2], `dev 2` = m[, 3], check.names = FALSE)
  t3 <- sc_from_wide(d)
  expect_equal(rownames(t3), c("2019", "2020", "2021"))
  expect_equal(names(t3), c("0", "1", "2"))
  expect_equal(as.matrix(sc_df(t3)), as.matrix(sc_df(t1)), ignore_attr = TRUE)
  d2 <- data.frame(a = m[, 1], b = m[, 2], c = m[, 3])
  expect_equal(names(sc_from_wide(d2)), c("0", "1", "2"))
  expect_error(sc_from_wide(m, origins = 1:2), "one label per row")
  cl <- sc_chain_ladder(m)  # plain matrix works everywhere
  expect_equal(cl$table$origin, c("0", "1", "2", "total"))
  expect_false(sc_is_cumulative(rbind(c(100, 50), c(110, NA))))
  expect_true(sc_is_cumulative(rbind(c(100, 150), c(110, NA))))
})

test_that("wiring like the IDE fixture: 3 origins, reserve summary", {
  df <- data.frame(origin_year = c(2019, 2019, 2019, 2020, 2020, 2021), dev_period = c(0, 1, 2, 0, 1, 0), paid = c(100, 50, 25, 110, 50, 120))
  tri <- sc_triangle(df)
  m <- sc_mack(tri)
  expect_true(m$se > 0 && m$se < m$ibnr && m$cv > 0 && m$cv < 1)
  m2 <- sc_mack(df)  # the long file goes straight in
  expect_equal(m2$ibnr, m$ibnr)
  r <- sc_reserve(df, n_boot = 200)
  expect_s3_class(r, "scelo_table")
  expect_setequal(r$method, c("chain-ladder", "mack", "bornhuetter-ferguson", "bootstrap"))
  expect_equal(names(r), c("method", "latest", "ultimate", "ibnr", "se", "cv", "p95", "p99"))
  expect_equal(r$ibnr[r$method == "chain-ladder"], r$ibnr[r$method == "mack"])
  expect_equal(r$ibnr[r$method == "bornhuetter-ferguson"], r$ibnr[r$method == "chain-ladder"])
  expect_true(is.na(r$se[1]) && !is.na(r$se[2]) && !is.na(r$p95[4]))
  expect_equal(attr(r, "title"), "Reserve summary")
  expect_equal(attr(r, "basis"), "paid · origin_year × dev")
  expect_match(sc_notes(r)[1], "^Triangle: 3 origins × 3 lags\\. Mack SE ±1\\.96 → \\[.*\\]; bootstrap p95 .*\\.$")
  res <- attr(r, "results")
  expect_named(res, c("chain_ladder", "mack", "bf", "bootstrap", "triangle"))
  expect_s3_class(res$mack, "scelo_reserving")
  r2 <- sc_reserve(tri, n_boot = 100, seed = 3)
  expect_equal(r2$ibnr[2], r$ibnr[2])
})

test_that("tail factor", {
  f <- c(1.5, 1.2, 1.1, 1.05, 1.02)
  t <- sc_tail(f)
  expect_true(t > 1.0 && t < 1.1)
  expect_close(t, golden()$raa$tail_exp, 1e-10, "tail")
  expect_equal(sc_tail(c(1.0, 1.0)), 1.0)
  expect_gt(sc_tail(f, method = "power"), 1)
  expect_gt(sc_tail(f, n_fit = 3), 1)
  expect_equal(sc_tail(f, horizon = 0), 1)
  expect_gt(sc_tail(1.2), 1)  # a single factor: minimum-norm fit, like numpy lstsq
})

test_that("print and summary of a reserving result", {
  raa <- raa_triangle()
  m <- sc_mack(raa)
  out <- capture.output(print(m))
  expect_equal(out[1], "mack: IBNR 52,135 · ultimate 213,122 · latest 160,987 · SE 26,909 (CV 51.6%)")
  expect_true(any(grepl("Mack chain ladder", out)))
  cl <- sc_chain_ladder(raa)
  expect_equal(capture.output(print(cl))[1], "chain-ladder: IBNR 52,135 · ultimate 213,122 · latest 160,987")
  s <- summary(m)
  expect_equal(names(s), c("method", "latest", "ultimate", "ibnr", "se", "cv"))
  expect_equal(nrow(s), 1)
  expect_equal(names(summary(cl)), c("method", "latest", "ultimate", "ibnr"))
})

test_that("reserving tools land in the audit trail", {
  sc_clear_audit()
  raa <- raa_triangle()
  sc_mack(raa)
  sc_bootstrap(raa, n = 20, seed = 1)
  a <- sc_audit()
  expect_equal(a$fn, c("sc_mack", "sc_bootstrap"))
  expect_equal(a$in_shape, c("10×10", "10×10"))
  expect_equal(a$out_shape, c("11×8", "11×7"))
  expect_match(a$args[2], "n=20, seed=1")
})
