test_that("every sc_plot_* draws without error", {
  grDevices::pdf(NULL)
  on.exit(grDevices::dev.off(), add = TRUE)
  claims <- sc_sample("claims")
  claims$settled <- as.integer(claims$settled == "yes")
  claims$n <- as.integer(claims$paid > 20000)
  mp <- sc_sample("lifelib-mp")
  expect_silent(sc_plot_bars(table(claims$line), title = "Policies by line"))
  expect_silent(sc_plot_bars(table(claims$line), highlight = "motor"))
  r <- sc_plot_rates(claims, "line", "settled", title = "Settlement rate")
  expect_equal(nrow(r), 5)
  m <- sc_glm(claims, "n ~ C(line) + C(sex) + age", "poisson")
  rel <- sc_plot_relativities(m)
  expect_named(rel, c("line", "sex", "numeric (per unit)"))
  a <- sc_plot_projection(sc_basicterm(mp))
  expect_true(all(c("premiums", "claims", "expenses") %in% names(a)))
  expect_silent(sc_plot_scr(sc_scr_life(mp)))
  expect_silent(sc_plot_csm(sc_csm(mp, sc_basicterm_assumptions(premium_mult = 3), ra = 0.05)))
  expect_silent(sc_plot_lines(sc_df(sc_discount_curve(0.04, max_tenor = 20)), "tenor", c("discount factor", "1y forward")))
  expect_silent(sc_plot_triangle(sc_triangle(claims)))
  expect_error(sc_plot_lines(data.frame(x = 1:2, a = 1:2, b = 1:2, c = 1:2, d = 1:2, e = 1:2, f = 1:2), "x", c("a", "b", "c", "d", "e", "f")), "at most five")
})

test_that("the palette is the validated set and relativities name the base level", {
  p <- sc_palette()
  expect_equal(p$series[1:3], c("#1F8F5C", "#345DCB", "#C4631F"))
  expect_length(p$sequential, 5)
  claims <- sc_sample("claims")
  claims$n <- as.integer(claims$paid > 20000)
  m <- sc_glm(claims, "n ~ C(line)", "poisson", base = "first")
  expect_equal(m$base_levels$line, "engineering")
  expect_equal(sc_relativities(m)$level[1], "engineering (base)")
})
