# Life: every number against the Python package (py_golden.json) plus the
# invariants tests/test_life.py checks.

test_that("life table matches the Python golden table", {
  g <- golden()
  lt <- sc_life_table()
  G <- split_df(g$life_table_makeham)
  expect_equal(names(lt), names(G))
  for (c in names(G)) expect_close(lt[[c]], G[[c]], 1e-9, label = c)
})

test_that("life table invariants hold", {
  lt <- sc_life_table()
  expect_s3_class(lt, "scelo_table")
  expect_equal(nrow(lt), 91)
  expect_equal(lt$lx[1], 1e5)
  expect_equal(lt$qx[91], 1)
  expect_lt(abs(lt$ex[91] - 0.5), 1e-9)
  expect_close(lt$lx[-1], (lt$lx - lt$dx)[-91], 1e-9, label = "lx recursion")
  expect_close(lt$dx, lt$lx * lt$qx, 1e-9, label = "dx = lx qx")
  expect_lt(abs(lt$Tx[1] - sum(lt$Lx)), 1e-6)
  expect_lt(abs(lt$ex[1] - sum(lt$Lx) / 1e5), 1e-9)
  expect_true(all(diff(lt$qx[-91]) > 0))
  expect_true(any(grepl("ILLUSTRATIVE", sc_notes(lt), fixed = TRUE)))
  expect_equal(attr(lt, "title"), "Life table · Gompertz–Makeham (illustrative)")
  expect_equal(attr(lt, "stage"), "hard")
  small <- sc_life_table(ages = c(60, 100), radix = 1000)
  expect_equal(range(small$age), c(60, 100))
  expect_equal(small$lx[1], 1000)
  expect_true(grepl("Radix l(60) = 1,000; table closed at age 100", sc_notes(small)[2], fixed = TRUE))
})

test_that("sc_qx resolves every basis shape", {
  g <- golden()
  q <- sc_qx(data.frame(age = c(30, 30, 31, 33), qx = c(1.0, 1.2, 1.3, 1.5)))  # percent-shaped, with a gap
  expect_s3_class(q, "scelo_qx")
  expect_equal(q$ages, g$qx_interp$ages)
  expect_close(q$qx, g$qx_interp$qx, 1e-12)
  expect_lt(abs(q$qx[1] - 0.011), 1e-12)
  expect_lt(abs(q$qx[3] - 0.014), 1e-12)
  expect_true(32 %in% q$ages)
  expect_true(any(grepl("percentages", q$notes)))
  expect_true(any(grepl("1 missing age interpolated", q$notes)))
  q2 <- sc_qx(data.frame(age = c(40, 40, 41), deaths = c(1, 1, 3), exposure = c(200, 200, 600)))
  expect_lt(abs(q2$qx[1] - 0.005), 1e-12)
  expect_true(grepl("ungraduated", q2$notes[1]))
  expect_equal(q2$label, "crude qx = `deaths` / `exposure` by `age`")
  q3 <- sc_qx(data.frame(age = c(50, 51, 52), lx = c(1000, 990, 975)))
  expect_lt(abs(q3$qx[1] - 0.01), 1e-12)
  expect_equal(q3$label, "qx derived from `lx` by `age`")
  expect_error(sc_qx(data.frame(foo = 1)), "could not infer the age column")
  # named vector, parameter list, strings
  qv <- sc_qx(stats::setNames(c(0.01, 0.02, 0.04), c(30, 31, 33)))
  expect_equal(qv$ages, 30:33)
  expect_equal(qv$qx, c(0.01, 0.02, 0.03, 0.04))
  expect_equal(qv$label, "qx from `qx` by age")
  qm <- sc_qx()
  expect_equal(qm$ages, 20:110)
  expect_equal(qm$label, "Gompertz–Makeham (illustrative)")
  expect_close(qm$qx, unname(sc_makeham(20:110)), 1e-15)
  qc <- sc_qx(list(A = 0.0003, B = 3e-6, c = 1.12, multiplier = 1.5), ages = c(30, 40))
  expect_equal(qc$label, "Gompertz–Makeham (custom)")
  expect_equal(qc$notes, "Mortality from Gompertz–Makeham μx = A + B·cˣ with A = 0.0003, B = 3e-06, c = 1.12, × 1.5.")
  expect_close(qc$qx[1:3], c(0.00059258, 0.0006097, 0.00062888), 1e-6)
  qg <- sc_qx("gompertz", ages = c(30, 32))
  expect_close(qg$qx, c(9.54910686e-05, 1.07331326e-04, 1.20639607e-04), 1e-7)
  expect_close(unname(sc_gompertz(30:32)), qg$qx, 1e-12)
  expect_identical(sc_qx(qm), qm)
  expect_equal(range(sc_qx(ages = c(NA, 50))$ages), c(20, 50))
  expect_equal(range(sc_qx(ages = c(90, NA))$ages), c(90, 110))
  expect_error(sc_qx(ages = 30), "ages must be c(from, to)", fixed = TRUE)
  expect_error(sc_qx("AM92"), "unknown mortality basis")
  expect_error(sc_qx(stats::setNames(c(0.01, 0.02), c(30, 31)), ages = c(50, 60)), "no ages left")
  expect_identical(sc_qx(qv, ages = c(50, 60)), qv)  # a resolved scelo_qx passes through untouched, like Python's QxTable
  expect_equal(names(as.data.frame(qm)), c("age", "qx"))
  expect_output(print(qm), "Gompertz")
})

test_that("column names pass through ... to sc_qx (keyword-only, not partially matched to ages)", {
  lt <- sc_life_table(data.frame(Age = 60:70, Qx = 60:70 / 1000), age = "Age")
  expect_equal(attr(lt, "basis"), "qx from `Qx` by `Age`")
  expect_equal(lt$age, 60:70)
  cm <- sc_commutation(data.frame(Age = 60:70, Rate = 60:70 / 1000), age = "Age", qx_col = "Rate", i = 0.03)
  expect_equal(attr(cm, "basis"), "qx from `Rate` by `Age` · i = 3 %")
})

test_that("commutation functions match the golden table and their identities", {
  g <- golden()
  cm <- sc_commutation(i = 0.04)
  G <- split_df(g$commutation_4pct)
  expect_equal(names(cm), names(G))
  for (c in names(G)) expect_close(cm[[c]], G[[c]], 1e-9, label = c)
  expect_lt(abs(cm$Nx[1] - sum(cm$Dx)), 1e-6)
  expect_lt(abs(cm$Mx[1] - sum(cm$Cx)), 1e-6)
  expect_lt(abs(cm$Rx[1] - sum(cm$Mx)), 1e-6)
  expect_lt(abs(cm$Sx[1] - sum(cm$Nx)), 1e-6)
  expect_close(cm$Cx / cm$Dx, (cm$dx / cm$lx) / 1.04, 1e-9, label = "Cx/Dx")
  expect_equal(attr(cm, "title"), "Commutation functions · Gompertz–Makeham (illustrative) · i = 4 %")
  expect_true(grepl("Interest 4 % p.a.; v^x is measured from the first tabulated age (20)", sc_notes(cm)[2], fixed = TRUE))
})

test_that("factors match the golden table and the actuarial identities", {
  g <- golden()
  f <- sc_factors(i = 0.04, n = 10)
  G <- split_df(g$factors_4pct_n10)
  expect_equal(names(f), c("age", "äx", "ax", "Ax", "äx:10", "A¹x:10", "10Ex", "Ax:10"))
  expect_equal(names(f), names(G))
  for (c in names(G)) expect_close(f[[c]], G[[c]], 1e-9, label = c)
  d <- 0.04 / 1.04
  expect_close(f$Ax, 1 - d * f[["äx"]], 1e-9, label = "Ax = 1 - d ax")
  expect_close(f$ax, f[["äx"]] - 1, 1e-9, label = "ax = äx - 1")
  ok <- !is.na(f[["Ax:10"]])
  expect_close(f[["Ax:10"]][ok], f[["A¹x:10"]][ok] + f[["10Ex"]][ok], 1e-9, label = "Ax:n = A1x:n + nEx")
  expect_equal(sum(is.na(f[["Ax:10"]])), 10)  # blank where x + n runs past the table
  expect_equal(ncol(sc_factors(i = 0.04)), 4)
  expect_equal(attr(f, "title"), "Annuity & assurance factors · Gompertz–Makeham (illustrative) · i = 4 % · n = 10")
  expect_error(sc_factors(n = -1), "n must be")
})

test_that("premium grid matches the golden tables and the factor identity", {
  g <- golden()
  p <- sc_premium(i = 0.04, product = "term")
  e <- sc_premium(i = 0.04, product = "endowment")
  Gp <- split_df(g$premium_term_4pct)
  Ge <- split_df(g$premium_endow_4pct)
  expect_equal(names(p), c("age", "n=10", "n=15", "n=20", "n=25", "n=30"))
  for (c in names(Gp)) expect_close(p[[c]], Gp[[c]], 1e-9, label = c)
  for (c in names(Ge)) expect_close(e[[c]], Ge[[c]], 1e-9, label = c)
  f <- sc_df(sc_factors(i = 0.04, n = 10))
  row <- f[f$age == 30, ]
  expect_lt(abs(p[p$age == 30, "n=10"] - 1000 * row[["A¹x:10"]] / row[["äx:10"]]), 1e-9)
  expect_true(all(e[["n=10"]] > p[["n=10"]]))
  w <- sc_premium(i = 0.04, product = "whole-life")
  expect_true("whole life" %in% names(w))
  expect_equal(names(sc_premium(product = "Whole Life")), names(w))
  expect_lt(abs(sc_annuity(65, i = 0.04) - f[f$age == 65, "äx"]), 1e-12)
  expect_lt(abs(sc_annuity(65, i = 0.04, due = FALSE) - f[f$age == 65, "ax"]), 1e-12)
  expect_lt(abs(sc_annuity(40, i = 0.04, n = 10) - f[f$age == 40, "äx:10"]), 1e-12)
  expect_lt(abs(sc_assurance(40, i = 0.04) - f[f$age == 40, "Ax"]), 1e-12)
  expect_lt(abs(sc_assurance(40, i = 0.04, n = 10) - f[f$age == 40, "A¹x:10"]), 1e-12)
  expect_lt(abs(sc_assurance(40, i = 0.04, n = 10, endowment = TRUE) - f[f$age == 40, "Ax:10"]), 1e-12)
  expect_error(sc_annuity(200), "age 200 is not in the basis")
  expect_error(sc_premium(product = "annuity"), "product must be term, endowment or whole-life")
  expect_equal(attr(p, "title"), "Net premium per 1,000 SA · term assurance · Gompertz–Makeham (illustrative) · i = 4 %")
  expect_equal(sc_notes(p)[3], "Interest 4 %.")
  # a data-frame basis narrower than the default grid: rows outside the basis are skipped
  pd <- sc_premium(data.frame(age = 20:79, qx = unname(sc_makeham(20:79))), ages = c(30, 40), step = 5, terms = c(10, 20))
  expect_equal(pd$age, c(30, 35, 40))
  expect_close(pd[["n=20"]], c(0.510612, 0.747492, 1.171108), 1e-6)
})

test_that("actual vs expected matches the golden table", {
  g <- golden()
  exp_df <- data.frame(age = rep(60:69, each = 3), deaths = rep(c(1, 0, 2), 10), exposure = 100)
  a <- sc_ae(exp_df)
  G <- split_df(g$ae)
  expect_equal(names(a), names(G))
  expect_equal(a[["age band"]], c("60–64", "65–69", "total"))
  for (c in names(G)[-1]) expect_close(a[[c]], G[[c]], 1e-9, label = c)
  expect_lt(abs(a[["actual deaths"]][3] - 30), 1e-9)
  expect_equal(attr(a, "title"), "Actual vs expected · deaths / exposure vs Gompertz–Makeham (illustrative)")
  by <- sc_ae(data.frame(age = c(60, 61, 62, 60, 61, 62), deaths = c(1, 0, 2, 1, 1, 0), exposure = 100, sex = c("M", "M", "M", "F", "F", "F")), by = "sex")
  expect_equal(names(by)[1], "sex")
  expect_equal(by$sex, c("F", "M", "all"))
  expect_close(by[["expected deaths"]], c(1.142342, 1.142342, 2.284684), 1e-6)
  expect_close(by[["A/E"]], c(1.750789, 2.626184, 2.188487), 1e-6)
  # a custom expected basis: A/E of 1 when actual = expected exactly
  q <- sc_qx(data.frame(age = 60:69, qx = 0.01))
  same <- sc_ae(data.frame(age = 60:69, deaths = 1, exposure = 100), expected = q)
  expect_close(same[["A/E"]], rep(1, 3), 1e-12)
})

test_that("model points match the golden grouping", {
  g <- golden()
  mp <- sc_model_points(sc_sample("lifelib-mp"))
  G <- split_df(g$model_points)
  expect_equal(names(mp), names(G))
  for (c in names(G)) {
    if (is.numeric(G[[c]])) expect_close(mp[[c]], G[[c]], 1e-9, label = c) else expect_equal(as.character(mp[[c]]), as.character(G[[c]]))
  }
  expect_equal(sum(mp$policy_count), 100)
  expect_lt(abs(sum(mp$sum_assured) - sum(sc_sample("lifelib-mp")$sum_assured)), 1e-6)
  expect_equal(attr(mp, "title"), "Model points · 100 policies → 66 groups")
  odd <- sc_model_points(data.frame(age = c(30, 31, 44, 45, 52), sex = c("m", "Female", NA, "", "F"), term = c(10, 10, NA, 20, NA), sum_assured = c(100, 200, 300, 400, 500)))
  expect_equal(odd$sex, c("F", "M", "?", "?", "F"))
  expect_equal(odd$policy_term, c(10, 10, NA, 20, NA))
  expect_equal(odd$age_band, c("30–34", "30–34", "40–44", "45–49", "50–54"))
})

test_that("survival helpers", {
  q <- c(0.1, 0.2, 1.0)
  s <- sc_survival(q)
  expect_equal(length(s), 4)
  expect_lt(abs(s[[2]] - 0.9), 1e-12)
  expect_lt(abs(s[[3]] - 0.72), 1e-12)
  expect_equal(s[[4]], 0)
  expect_lt(abs(sc_survival(q, t = 2) - 0.72), 1e-12)
  expect_lt(abs(sc_life_expectancy(q, curtate = TRUE) - (0.9 + 0.72)), 1e-12)
  expect_lt(abs(sc_life_expectancy(q) - (0.9 + 0.72 + 0.5)), 1e-12)
  expect_lt(abs(sc_life_expectancy(sc_makeham(40:110)) - 46.277647296678694), 1e-9)
  closed <- sc_close_table(stats::setNames(c(0.1, 0.2, 0.3), 60:62))
  expect_equal(closed[[3]], 1)
  expect_equal(names(closed), c("60", "61", "62"))
  expect_equal(unname(sc_close_table(stats::setNames(c(0.1, 0.2, 0.3, 0.4), 60:63), omega = 62)), c(0.1, 0.2, 1))
})

test_that("Whittaker-Henderson graduation reproduces the Python numbers and smooths", {
  g <- golden()
  crude <- stats::setNames(g$graduate$crude, g$graduate$ages)
  gr <- sc_graduate(crude, h = 100)
  expect_equal(names(gr), c("age", "crude", "graduated", "residual", "weight"))
  expect_equal(gr$age, g$graduate$ages)
  expect_close(gr$graduated, g$graduate$graduated, 1e-8)
  true <- unname(sc_makeham(30:89))
  expect_lt(mean(abs(log(gr$graduated) - log(true))), mean(abs(log(crude) - log(true))))
  expect_true(all(gr$graduated > 0))
  expect_equal(attr(gr, "title"), "Whittaker–Henderson graduation · h = 100, z = 2")
  expect_equal(attr(gr, "basis"), "WH(h=100, z=2) on log qx")
  # data-frame input: exposure weights, a gap gets weight 0 (same as Python)
  gd <- sc_graduate(data.frame(age = c(50, 50, 51, 53, 54), deaths = c(1, 2, 3, 2, 4), exposure = c(100, 100, 150, 120, 130)), h = 10)
  expect_close(gd$weight, c(1.3333333, 1, 0, 0.8, 0.8666667), 1e-6)
  expect_close(gd$graduated, c(0.01544487, 0.01752500, 0.01980794, 0.02250986, 0.02595993), 1e-6)
  lin <- sc_graduate(crude, h = 100, log = FALSE)
  expect_equal(attr(lin, "basis"), "WH(h=100, z=2)")
})

test_that("Lee-Carter matches the Python fit and recovers a known drift", {
  g <- golden()
  lc <- sc_lee_carter(split_df(g$lee_carter$data), horizon = 5)
  expect_s3_class(lc, "scelo_lee_carter")
  expect_close(lc$ax, g$lee_carter$ax, 1e-9, label = "ax")
  expect_close(lc$bx, g$lee_carter$bx, 1e-9, label = "bx")
  expect_close(lc$kt, g$lee_carter$kt, 1e-9, label = "kt")
  expect_close(lc$drift, g$lee_carter$drift, 1e-9)
  expect_close(lc$drift_se, g$lee_carter$drift_se, 1e-9)
  G <- split_df(g$lee_carter$forecast)
  expect_equal(names(lc$forecast), c("year", "kt", "rate@65", "lower95", "upper95"))
  for (c in names(G)) expect_close(lc$forecast[[c]], G[[c]], 1e-9, label = c)
  expect_equal(names(lc$ax), as.character(50:90))
  expect_equal(names(lc$kt), as.character(1990:2019))
  # the Python test: synthetic log-linear improvement of 1.5 % a year
  d <- expand.grid(year = 1990:2019, age = 50:90)
  d$qx <- exp(-9 + 0.09 * d$age - 0.015 * (d$year - 1990))
  lc2 <- sc_lee_carter(d, horizon = 5)
  expect_lt(abs(sum(lc2$bx) - 1), 1e-9)
  expect_lt(abs(mean(lc2$kt)), 1e-9)
  expect_gt(lc2$explained, 0.99)
  imp <- 1 - (lc2$forecast[["rate@65"]][5] / lc2$forecast[["rate@65"]][1])^(1 / 4)
  expect_lt(abs(imp - (1 - exp(-0.015))), 1e-3)
  expect_output(print(lc2), "Lee–Carter: 41 ages × 30 years")
  expect_error(sc_lee_carter(d[d$year < 1992, ]), "at least 3 years")
})

test_that("Kaplan-Meier gives the textbook values", {
  g <- golden()
  km <- sc_kaplan_meier(data.frame(time = c(1, 2, 2, 3, 5, 8, 8, 9), status = c(1, 1, 0, 1, 0, 1, 1, 0)))
  G <- split_df(g$km)
  expect_equal(names(km), names(G))
  for (c in names(G)) expect_close(km[[c]], G[[c]], 1e-9, label = c)
  expect_close(km$S, c(0.875, 0.75, 0.6, 0.2), 1e-12)
  expect_equal(km$at_risk, c(8L, 7L, 5L, 3L))
  expect_equal(km$censored, c(0L, 1L, 0L, 0L))
  expect_equal(attr(km, "basis"), "time / status")
  by <- sc_kaplan_meier(data.frame(time = c(1, 2, 2, 3, 5, 8, 8, 9, 4, 6), status = c(1, 1, 0, 1, 0, 1, 1, 0, 1, 0), g = rep(c("A", "B"), 5)), by = "g")
  expect_equal(by$g, c("A", "A", "A", "B", "B", "B"))
  expect_close(by$S, c(0.8, 0.5333333, 0, 0.8, 0.6, 0.3), 1e-6)
  expect_close(by$lower95, c(0.203798, 0.068327, 0, 0.203798, 0.125723, 0.0123), 1e-5)
  expect_equal(attr(by, "title"), "Kaplan–Meier survival by g")
  words <- sc_kaplan_meier(data.frame(time = c(1, 2, 3), status = c("died", "no", "TRUE")))
  expect_equal(words$events, c(1L, 1L))
})

test_that("exposure splits at birthdays and allocates the death to the exit age", {
  ex <- sc_exposure(data.frame(start = "2020-01-01", end = "2022-01-01", age = 40.5, died = 1), "start", "end", event = "died")
  e <- stats::setNames(ex$exposure, ex$age)
  expect_lt(abs(e[["40"]] - 0.5), 1e-6)
  expect_lt(abs(e[["41"]] - 1.0), 1e-6)
  expect_lt(abs(e[["42"]] - 0.5), 2e-3)  # 2020 is a leap year
  expect_equal(ex$deaths[ex$age == 42], 1)
  expect_equal(names(ex), c("age", "exposure", "deaths", "crude_qx"))
  by <- sc_exposure(data.frame(start = c("2020-01-01", "2020-06-15"), end = c("2022-01-01", "2021-03-01"), age = c(40.5, 33), died = c(1, 0)), "start", "end", event = "died", by_year = TRUE)
  expect_equal(by$age, c(33, 40, 41, 42, 42))
  expect_equal(by$year, c(2020, 2020, 2020, 2021, 2022))
  expect_close(by$exposure, c(0.709103, 0.5, 1, 0.501369, 0), 1e-6)
  expect_equal(by$deaths, c(0, 0, 0, 0, 1))
  expect_true(is.na(by$crude_qx[5]))
  expect_equal(attr(by, "title"), "Central exposure by age × year")
  dob <- sc_exposure(data.frame(s = as.Date("2021-03-01"), e = as.Date("2021-09-01"), b = as.Date("1981-03-01")), "s", "e", birth = "b")
  expect_equal(dob$age, 40)
  expect_lt(abs(dob$exposure - 184 / 365.25), 1e-9)
  expect_equal(nrow(sc_exposure(data.frame(start = "2020-01-01", end = "2019-01-01", age = 40), "start", "end")), 0)
})

test_that("BasicTerm projection matches the Python port and the IDE's expectations", {
  g <- golden()
  mp <- sc_sample("lifelib-mp")
  bt <- sc_basicterm(mp)
  pv <- attr(bt, "pv")
  expect_close(unlist(pv[c("premiums", "claims", "expenses", "net")]), unlist(g$basicterm$pv[c("premiums", "claims", "expenses", "net")]), 1e-9)
  expect_equal(nrow(bt), g$basicterm$months)
  G <- split_df(g$basicterm$first)
  expect_equal(names(bt), names(G))
  for (c in names(G)) expect_close(bt[[c]][1:3], G[[c]], 1e-9, label = c)
  expect_lt(pv$net, 0)
  expect_lt(pv$premiums, pv$claims)  # the IDE's live test: this sample is under-priced
  expect_gt(nrow(bt), 120)
  expect_true(grepl("model-point file", attr(bt, "basis"), fixed = TRUE))
  expect_true(is.na(attr(bt, "break_even_month")))
  expect_true(grepl("break-even month never", sc_notes(bt)[1], fixed = TRUE))
  expect_equal(attr(bt, "title"), "BasicTerm projection · 100 model points · 360 months")
  no_prem <- sc_basicterm(mp[, setdiff(names(mp), "premium_pp")])
  expect_true(grepl("loading", attr(no_prem, "basis"), fixed = TRUE))
  expect_lt(attr(no_prem, "pv")$premiums, pv$premiums)
  # assumptions: partial override, unknown names rejected, annual premium column divided by 12
  cheap <- sc_basicterm(mp, list(lapse_rate = 0))
  expect_gt(attr(cheap, "pv")$premiums, pv$premiums)
  expect_error(sc_basicterm(mp, list(lapse = 0.1)), "unknown assumption")
  mpa <- mp
  names(mpa)[names(mpa) == "premium_pp"] <- "annual_premium"
  mpa$annual_premium <- mpa$annual_premium * 12
  expect_close(attr(sc_basicterm(mpa), "pv")$premiums, pv$premiums, 1e-9)
  expect_error(sc_basicterm(data.frame(age_at_entry = 0, sum_assured = 1, policy_term = 1)), "no usable model points")
})

test_that("the audit trail records the life tools", {
  sc_clear_audit()
  sc_life_table()
  sc_basicterm(sc_sample("lifelib-mp"))
  a <- sc_audit()
  expect_true(all(c("sc_life_table", "sc_basicterm") %in% a$fn))
  expect_equal(a$out_shape[a$fn == "sc_life_table"], "91×8")
})
