# Risk: tail measures, aggregate loss, fits, credibility, capital aggregation.
# Golden values come from the Python package (tests/testthat/fixtures/py_golden.json).

test_that("sc_var is the type-7 quantile and sc_tvar sits above it", {
  x <- as.numeric(1:1000)
  expect_equal(sc_var(x, 0.99), unname(stats::quantile(x, 0.99, type = 7)))
  expect_true(sc_tvar(x, 0.99) >= sc_var(x, 0.99))
  expect_identical(sc_es, sc_tvar)
  expect_equal(sc_var(c(x, NA), 0.5), sc_var(x, 0.5))
  expect_equal(sc_tvar(x, 0.999), mean(x[x >= stats::quantile(x, 0.999)]))
})

test_that("aggregate loss methods agree with theory", {
  lam <- 5; mu <- 8; sig <- 1
  mean_theory <- lam * exp(mu + sig^2 / 2)
  sd_theory <- sqrt(lam * exp(2 * mu + 2 * sig^2))
  for (method in c("panjer", "fft")) {
    a <- sc_aggregate_loss("poisson", "lognormal", lam = lam, mu = mu, sigma = sig, method = method)
    expect_true(abs(attr(a, "mean") / mean_theory - 1) < 2e-3, label = method)
    expect_true(abs(attr(a, "sd") / sd_theory - 1) < 5e-3, label = method)
    expect_s3_class(a, "scelo_table")
    expect_equal(names(a), c("p", "VaR", "TVaR"))
    expect_true(all(a$TVaR >= a$VaR))
    expect_match(sc_basis(a), sprintf("^%s · lattice h = ", method))
  }
  mc <- sc_aggregate_loss("poisson", "lognormal", lam = lam, mu = mu, sigma = sig, method = "mc", n_sims = 50000, seed = 1)
  expect_true(abs(attr(mc, "mean") / mean_theory - 1) < 0.03)
  expect_equal(sc_basis(mc), "Monte Carlo · 50,000 simulations")
  nb <- sc_aggregate_loss("negbin", "gamma", r = 3, beta = 2, alpha = 2, theta = 1000)
  expect_true(abs(attr(nb, "mean") - 12000) < 20)
  expect_true(all(nb$TVaR >= nb$VaR))
  expect_equal(sc_title(nb), "Aggregate loss · negbin(r=3, beta=2) × gamma")
})

test_that("Panjer golden values: poisson × lognormal and negbin × gamma", {
  g <- golden()
  a <- sc_aggregate_loss("poisson", "lognormal", lam = 5, mu = 8, sigma = 1, h = 100, n = 4096)
  gt <- split_df(g$panjer$table)
  expect_close(a$p, gt$p)
  expect_close(a$VaR, gt$VaR)
  expect_close(a$TVaR, gt$TVaR)
  expect_close(attr(a, "mean"), g$panjer$mean)
  expect_close(attr(a, "sd"), g$panjer$sd)
  expect_equal(sc_title(a), "Aggregate loss · poisson(lam=5) × lognormal")
  expect_equal(sc_basis(a), "panjer · lattice h = 100 × 4096")
  expect_equal(sc_notes(a), "Mean 24,572.33 · sd 18,099.39 · CV 0.737.")
  nb <- sc_aggregate_loss("negbin", "gamma", r = 3, beta = 2, alpha = 2, theta = 1000, h = 50)
  expect_close(attr(nb, "mean"), g$panjer_nb$mean)
  expect_close(attr(nb, "sd"), g$panjer_nb$sd)
  expect_close(nb$VaR[nb$p == 0.995], g$panjer_nb$var995)
})

test_that("other frequencies, empirical severities and the lattice warning", {
  b <- sc_aggregate_loss("binomial", "exponential", m = 10, q = 0.3, theta = 500)
  expect_true(abs(attr(b, "mean") - 10 * 0.3 * 500) < 5)
  bf <- sc_aggregate_loss("binomial", "exponential", m = 10, q = 0.3, theta = 500, method = "fft")
  expect_true(abs(attr(bf, "mean") - attr(b, "mean")) < 1)
  set.seed(7)
  emp <- stats::rgamma(500, 2, scale = 1000)
  e <- sc_aggregate_loss("poisson", emp, lam = 4)
  expect_true(abs(attr(e, "mean") - 4 * mean(emp)) < 0.02 * 4 * mean(emp))
  expect_equal(sc_title(e), "Aggregate loss · poisson(lam=4) × empirical")
  w <- sc_aggregate_loss("poisson", "weibull", lam = 2, shape = 1.5, scale = 1000)
  expect_true(abs(attr(w, "mean") - 2 * 1000 * gamma(1 + 1 / 1.5)) < 5)
  p <- sc_aggregate_loss("negbin", "pareto", r = 2, beta = 1, alpha = 3, theta = 1000, method = "fft")
  expect_true(abs(attr(p, "mean") - 2 * 500) < 10)
  short <- sc_aggregate_loss("poisson", "lognormal", lam = 5, mu = 8, sigma = 1, h = 10, n = 256)
  expect_match(sc_basis(short), "WARNING lattice too short")
  expect_error(sc_aggregate_loss("geometric", "lognormal", lam = 1, mu = 1, sigma = 1), "Panjer frequency must be poisson, negbin or binomial")
  expect_error(sc_aggregate_loss("poisson", "cauchy", lam = 1), "severity must be lognormal, exponential, gamma, pareto or weibull")
})

test_that("sc_panjer reproduces the pmf identities", {
  f <- c(0, 0.5, 0.3, 0.2, rep(0, 396))
  g <- sc_panjer("poisson", f, lam = 2)
  expect_equal(sum(g), 1, tolerance = 1e-12)
  expect_equal(sum((seq_along(g) - 1) * g), 2 * sum((seq_along(f) - 1) * f), tolerance = 1e-12)
  expect_equal(g[1], exp(-2))
  gn <- sc_panjer("negbin", f, r = 2, beta = 1.5)
  expect_equal(sum((seq_along(gn) - 1) * gn), 3 * sum((seq_along(f) - 1) * f), tolerance = 1e-12)
  gb <- sc_panjer("binomial", f, m = 5, q = 0.2)
  expect_equal(sum((seq_along(gb) - 1) * gb), 1 * sum((seq_along(f) - 1) * f), tolerance = 1e-12)
  expect_error(sc_panjer(c(0.5, 0.5), f), "pass a frequency name")
})

test_that("simulate_losses is seeded and near theory", {
  S <- sc_simulate_losses("poisson", "lognormal", lam = 5, mu = 8, sigma = 1, n_sims = 20000, seed = 3)
  expect_length(S, 20000)
  expect_identical(S, sc_simulate_losses("poisson", "lognormal", lam = 5, mu = 8, sigma = 1, n_sims = 20000, seed = 3))
  expect_true(abs(mean(S) / (5 * exp(8.5)) - 1) < 0.05)
  S2 <- sc_simulate_losses("binomial", "pareto", m = 10, q = 0.5, alpha = 3, theta = 100, n_sims = 5000, seed = 1)
  expect_true(abs(mean(S2) - 5 * 50) < 25)
})

test_that("sc_fit ranks the true family first", {
  set.seed(2)
  x <- stats::rlnorm(2000, 8, 1.2)
  f <- sc_fit(x)
  expect_s3_class(f, "scelo_table")
  expect_equal(f$distribution[1], "lognormal")
  expect_true(abs(f$p_mu[1] - 8) < 0.1 && abs(f$p_sigma[1] - 1.2) < 0.1)
  expect_true(all(diff(f$aic) >= 0))
  expect_true(all(f$ks > 0 & f$ks < 1))
  expect_equal(names(f)[1:5], c("distribution", "params", "loglik", "aic", "ks"))
  expect_equal(sc_title(f), "Severity fits · n = 2,000")
  expect_equal(sc_basis(f), "maximum likelihood")
  # closed forms
  lx <- log(x)
  expect_close(f$p_mu[1], mean(lx))
  expect_close(f$p_sigma[1], sqrt(mean((lx - mean(lx))^2)))
  expect_close(f$p_theta[f$distribution == "exponential"], mean(x))
  # the numerical fits satisfy their likelihood equations
  a <- f$p_alpha[f$distribution == "gamma"]
  expect_true(abs(log(a) - digamma(a) - (log(mean(x)) - mean(lx))) < 1e-8)
  k <- f$p_shape[f$distribution == "weibull"]
  expect_true(abs(sum(x^k * lx) / sum(x^k) - 1 / k - mean(lx)) < 1e-8)
  set.seed(4)
  gx <- stats::rgamma(3000, shape = 2, scale = 500)
  expect_equal(sc_fit(gx)$distribution[1], "gamma")
  ps <- sc_lognormal_params(1000, 500)
  expect_true(abs(exp(ps[["mu"]] + ps[["sigma"]]^2 / 2) - 1000) < 1e-9)
  expect_error(sc_fit(c(1, 2, 3)), "need at least 5 positive observations")
})

test_that("credibility golden values and classical standards", {
  g <- golden()
  df <- split_df(g$credibility$data)
  c <- sc_credibility(df, "group", "lr")
  expect_s3_class(c, "scelo_table")
  gt <- split_df(g$credibility$table)
  expect_equal(c$group, gt$group)
  for (col in c("n", "weight", "mean", "Z", "credibility_premium")) expect_close(c[[col]], gt[[col]], label = col)
  expect_equal(sc_basis(c), g$credibility$basis)
  expect_equal(sc_title(c), "Bühlmann–Straub credibility · lr by group")
  expect_equal(sc_credibility(df), c)   # inferred columns
  expect_identical(sc_buhlmann, sc_credibility)
  A <- c[c$group == "A", ]; C <- c[c$group == "C", ]
  expect_true(A$Z > C$Z && C$Z > 0 && A$Z <= 1)
  expect_true(abs(C$credibility_premium - C$mean) > 0)
  expect_equal(round(sc_full_credibility(0.9, 0.05)), 1082)
  expect_close(sc_full_credibility(0.9, 0.05), g$full_credibility)
  expect_true(abs(sc_limited_fluctuation(270.5, p = 0.9, k = 0.05) - 0.5) < 1e-2)
  expect_equal(sc_limited_fluctuation(1e9), 1)
  expect_true(sc_full_credibility(0.9, 0.05, cv = 1) > 2 * sc_full_credibility(0.9, 0.05) - 1e-9)
})

test_that("credibility handles weights, single-record groups and indistinguishable groups", {
  df <- data.frame(group = c("A", "A", "A", "B", "B", "C"), lr = c(0.7, 0.8, 0.75, 0.9, 0.95, 0.5), w = c(10, 20, 30, 5, 5, 1))
  c <- sc_credibility(df, "group", "lr", "w")
  expect_equal(c$group, c("A", "B", "C"))
  expect_equal(c$weight, c(60, 10, 1))
  expect_close(c$mean[1], sum(c(0.7, 0.8, 0.75) * c(10, 20, 30)) / 60)
  expect_true(all(c$Z >= 0 & c$Z <= 1))
  flat <- data.frame(group = rep(c("A", "B"), each = 4), lr = rep(c(0.5, 0.6, 0.5, 0.6), 2))
  f <- sc_credibility(flat)
  expect_equal(f$Z, c(0, 0))
  expect_match(sc_basis(f), "K inf$")
  expect_error(sc_credibility(data.frame(group = c("a", "b"), txt = c("x", "y"))), "pass value=<numeric column>")
})

test_that("aggregate_scr golden values and identity correlation", {
  g <- golden()
  t <- sc_aggregate_scr(c(mortality = 100, longevity = 50, lapse = 200, expense = 80, cat = 40))
  gt <- split_df(g$scr)
  expect_equal(t$module, gt$index)
  for (col in c("charge", "marginal", "share")) expect_close(t[[col]], gt[[col]], label = col)
  scr <- t$charge[t$module == "SCR"]
  expect_true(scr > 0 && scr < 470)
  expect_true(abs(sum(t$marginal, na.rm = TRUE) - scr) < 1e-9)
  expect_equal(sc_notes(t), "SCR = √(vᵀρv) = 304 vs undiversified sum 470 (35.3% diversification). Marginal contributions (Euler) sum to the SCR.")
  expect_equal(sc_basis(t), "SII life correlation matrix")
  ident <- sc_aggregate_scr(c(a = 3, b = 4), corr = diag(2))
  expect_true(abs(ident$charge[ident$module == "SCR"] - 5) < 1e-12)
  expect_equal(sc_basis(ident), "given correlation matrix")
  named <- sc_aggregate_scr(list(a = 3, b = 4), corr = matrix(c(1, 1, 1, 1), 2, dimnames = list(c("a", "b"), c("a", "b"))))
  expect_true(abs(named$charge[named$module == "SCR"] - 7) < 1e-12)
  bscr <- sc_aggregate_scr(c(market = 100, life = 50, non_life = 30), corr = SC_SII_BSCR_CORR)
  expect_true(bscr$charge[bscr$module == "SCR"] < 180)
  expect_equal(dim(SC_SII_LIFE_CORR), c(7, 7))
  expect_true(isSymmetric(SC_SII_LIFE_CORR) && isSymmetric(SC_SII_NONLIFE_CORR) && isSymmetric(SC_SII_BSCR_CORR))
  expect_error(sc_aggregate_scr(c(1, 2)), "modules must be named")
})

test_that("tools functions leave an audit trail", {
  sc_clear_audit()
  sc_aggregate_loss("poisson", "lognormal", lam = 2, mu = 5, sigma = 0.5, n = 512)
  sc_aggregate_scr(c(mortality = 1, lapse = 2))
  a <- sc_audit()
  expect_equal(a$fn, c("sc_aggregate_loss", "sc_aggregate_scr"))
  expect_equal(a$out_shape, c("6×3", "5×4"))
})
