# Pricing: GLM parity with the Python engine, relativities, prediction, lift,
# frequency / severity, loss ratio, burning cost.

motor_data <- function() {
  df <- split_df(golden()$glm$data)
  set.seed(5)
  df$y <- as.integer(stats::runif(nrow(df)) < stats::plogis(-1 + 0.03 * (df$age - 40)))
  df
}

test_that("poisson GLM with offset matches the Python golden values", {
  g <- golden()
  motor <- motor_data()
  m <- sc_glm(motor, "claims ~ C(region) + age", "poisson", offset = "exposure")
  expect_s3_class(m, "scelo_glm")
  gp <- unlist(g$glm$poisson$params)
  expect_equal(names(m$params), names(gp))
  expect_close(m$params, gp, 1e-6)
  expect_close(m$deviance, g$glm$poisson$deviance, 1e-6)
  expect_close(m$null_deviance, g$glm$poisson$null_deviance, 1e-6)
  expect_close(m$aic, g$glm$poisson$aic, 1e-6)
  expect_equal(m$n, 4000L)
  expect_equal(m$df_resid, 3996L)
  expect_equal(m$dispersion, 1)
  expect_equal(m$engine, "stats::glm")
  expect_equal(m$terms, c("region", "age"))
  expect_equal(m$levels, list(region = c("WC", "KZN")))
  expect_s3_class(m$coef, "scelo_table")
  expect_equal(names(m$coef), c("term", "estimate", "std_err", "z", "p_value", "exp"))
  expect_equal(m$coef$term, names(gp))
  expect_close(m$coef$exp, exp(m$coef$estimate))
  expect_true(all(m$coef$p_value >= 0 & m$coef$p_value <= 1))
  expect_close(m$coef$z, m$coef$estimate / m$coef$std_err)
  expect_equal(sc_title(m$coef), "GLM · poisson · claims ~ C(region) + age")
  expect_equal(sc_basis(m$coef), "poisson / log · stats::glm · offset log(exposure)")
  expect_equal(sc_notes(m$coef)[1], "n = 4,000, deviance 1,726.81 on 3996 df (null 1,765.35), dispersion 1, AIC 2,437.7.")
  expect_length(m$fitted, 4000)
  expect_close(sum(m$fitted), sum(motor$claims), 1e-6)   # log link with intercept: fitted totals balance
  expect_output(print(m), "GLM poisson \\(log\\) · claims ~ C\\(region\\) \\+ age · n = 4,000 · deviance 1,726.81 \\(null 1,765.35\\) · dispersion 1 · AIC 2,437.7 · stats::glm")
  # the same fit from an R formula object
  m2 <- sc_glm(motor, claims ~ C(region) + age, "poisson", offset = "exposure")
  expect_equal(m2$params, m$params)
})

test_that("gamma GLM matches the Python golden values", {
  g <- golden()
  motor <- motor_data()
  m <- sc_glm(motor, "sev ~ age + C(region)", "gamma")
  gp <- unlist(g$glm$gamma$params)
  expect_equal(names(m$params), names(gp))
  expect_close(m$params, gp, 1e-6)
  expect_close(m$deviance, g$glm$gamma$deviance, 1e-6)
  expect_close(m$dispersion, g$glm$gamma$dispersion, 1e-6)
  # Pearson dispersion, and the Python AIC definition (a = 1 / dispersion)
  expect_close(m$dispersion, sum((motor$sev - m$fitted)^2 / m$fitted^2) / m$df_resid, 1e-8)
  a <- 1 / m$dispersion
  ll <- sum(a * log(a * motor$sev / m$fitted) - a * motor$sev / m$fitted - log(motor$sev) - lgamma(a))
  expect_close(m$aic, 2 * 5 - 2 * ll, 1e-8)
  expect_equal(sc_basis(m$coef), "gamma / log · stats::glm")
})

test_that("every family fits and agrees with stats::glm", {
  motor <- motor_data()
  b <- sc_glm(motor, "y ~ age", "binomial")
  ref <- stats::glm(y ~ age, binomial, motor)
  expect_close(unname(b$params), unname(coef(ref)), 1e-6)
  expect_close(b$deviance, deviance(ref), 1e-8)
  expect_close(b$aic, AIC(ref), 1e-8)
  expect_null(b$coef$exp)
  n <- sc_glm(motor, "sev ~ age", "gaussian")
  refn <- stats::glm(sev ~ age, gaussian, motor)
  expect_close(unname(n$params), unname(coef(refn)), 1e-8)
  expect_close(n$aic, AIC(refn), 1e-8)
  expect_equal(n$link, "identity")
  ig <- sc_glm(motor, "sev ~ age", "inverse_gaussian")
  refi <- stats::glm(sev ~ age, inverse.gaussian(link = "log"), motor)
  expect_close(unname(ig$params), unname(coef(refi)), 1e-6)
  expect_true(is.na(ig$aic))
  gl <- sc_glm(motor, "sev ~ age", "gamma", link = "identity")
  expect_equal(gl$link, "identity")
  expect_error(sc_relativities(gl), "relativities need a log link")
  expect_error(sc_glm(motor, "sev ~ age", "lognormal"), "family must be one of poisson, gamma, gaussian, binomial, tweedie, inverse_gaussian")
  expect_error(sc_glm(motor, "sev + age", "gamma"), 'formula must look like "y ~ x1 \\+ C\\(x2\\)"')
  expect_error(sc_glm(motor, "sev ~ C(province)", "gamma"), "column 'province' is not in the data")
  expect_error(sc_glm(motor[1:4, ], "sev ~ age + C(region)", "gamma"), "only 4 usable rows for 4 parameters")
})

test_that("tweedie needs statmod", {
  skip_if_not_installed("statmod")
  motor <- motor_data()
  t <- sc_glm(motor, "sev ~ age", "tweedie", power = 1.5)
  expect_equal(t$power, 1.5)
  expect_true(is.na(t$aic))
  expect_close(t$dispersion, sum((motor$sev - t$fitted)^2 / t$fitted^1.5) / t$df_resid, 1e-8)
  g <- sc_glm(motor, "sev ~ age", "gamma")
  expect_true(abs(t$params[["age"]] - g$params[["age"]]) < 2e-3)
})

test_that("weights, missing rows and prior weights are handled", {
  motor <- motor_data()
  motor$w <- ifelse(motor$region == "GP", 2, 1)
  m <- sc_glm(motor, "claims ~ C(region) + age", "poisson", offset = "exposure", weights = "w")
  ref <- stats::glm(claims ~ I(region == "WC") + I(region == "KZN") + age + offset(log(exposure)), poisson, motor, weights = w)
  expect_close(unname(m$params), unname(coef(ref)), 1e-6)
  expect_equal(m$weights_col, "w")
  holes <- motor
  holes$age[1:10] <- NA
  holes$exposure[11:15] <- 0
  h <- sc_glm(holes, "claims ~ C(region) + age", "poisson", offset = "exposure")
  expect_equal(h$n, 3985L)
  gz <- motor
  gz$sev[1:5] <- 0
  expect_equal(sc_glm(gz, "sev ~ age", "gamma")$n, 3995L)
})

test_that("design matrix: categorical base level is the most frequent level", {
  df <- data.frame(y = 1:6, f = c("b", "a", "b", "c", "b", "a"), x = c(1, 2, 3, 4, 5, 6), flag = c(TRUE, FALSE, TRUE, TRUE, FALSE, TRUE))
  d <- sc_design_matrix(df, "y ~ C(f) + x + flag")
  expect_equal(colnames(d$X), c("Intercept", "f[a]", "f[c]", "x", "flag[FALSE]"))
  expect_equal(d$terms, c("f", "x", "flag"))
  expect_equal(d$levels, list(f = c("a", "c"), flag = "FALSE"))
  expect_equal(unname(d$X[, "f[a]"]), c(0, 1, 0, 0, 0, 1))
  expect_equal(d$y, as.numeric(1:6))
  full <- sc_design_matrix(df, "y ~ C(f)", drop_first = FALSE)
  expect_equal(colnames(full$X), c("Intercept", "f[b]", "f[a]", "f[c]"))
  fixed <- sc_design_matrix(df, "y ~ C(f)", levels = list(f = c("c", "zz")))
  expect_equal(colnames(fixed$X), c("Intercept", "f[c]", "f[zz]"))
  expect_equal(unname(colSums(fixed$X)), c(6, 1, 0))
  expect_equal(colnames(sc_design_matrix(df, "y ~ 1 + x")$X), c("Intercept", "x"))
})

test_that("relativities, prediction, rate table, lift and gini", {
  g <- golden()
  motor <- motor_data()
  m <- sc_glm(motor, "claims ~ C(region) + age", "poisson", offset = "exposure")
  rel <- sc_relativities(m)
  expect_s3_class(rel, "scelo_table")
  expect_equal(names(rel), c("factor", "level", "relativity", "estimate"))
  expect_equal(rel$relativity[rel$level == "(base)"], 1)
  expect_equal(rel$level, c("(base)", "WC", "KZN", "per unit"))
  expect_true(abs(rel$relativity[rel$level == "WC"] - exp(0.3)) < 0.15)
  expect_close(attr(rel, "base_rate"), exp(m$params[["Intercept"]]))
  expect_equal(sc_basis(rel), sprintf("base rate exp(intercept) = %.6g", exp(m$params[["Intercept"]])))
  pred <- sc_predict(m, head(motor, 5))
  expect_close(pred, m$fitted[1:5], 1e-10)
  expect_close(predict(m, head(motor, 5)), pred, 1e-12)
  # new data whose most frequent level differs from the training base still predicts correctly
  wc <- motor[motor$region != "GP", ][1:20, ]
  expect_close(sc_predict(m, wc), m$fitted[match(rownames(wc), rownames(motor))], 1e-10)
  expect_close(sc_predict(m, head(motor, 5), offset = rep(1, 5)), m$fitted[1:5] / motor$exposure[1:5], 1e-10)
  newdata <- head(motor, 3)[c("region", "age", "exposure")]
  expect_close(sc_predict(m, newdata), m$fitted[1:3], 1e-10)
  rt <- sc_rate_table(m)
  expect_equal(rownames(rt), c("(base)", "KZN", "WC", "per unit"))
  expect_equal(names(rt), c("age", "region"))
  expect_true(any(!is.na(rt["(base)", ])))
  expect_close(rt["WC", "region"], exp(m$params[["region[WC]"]]))
  lift <- sc_lift(motor$claims, m$fitted, bins = 5, exposure = motor$exposure)
  expect_s3_class(lift, "scelo_table")
  expect_equal(nrow(lift), 5)
  expect_equal(names(lift), c("band", "exposure", "actual", "predicted", "lift", "a/e"))
  gl <- split_df(g$glm$lift)
  for (col in names(gl)) expect_close(lift[[col]], gl[[col]], 1e-6, label = col)
  expect_true(lift$actual[5] > lift$actual[1])
  expect_equal(sc_title(lift), "Lift · 5 bands")
  expect_equal(sc_basis(lift), sprintf("Gini %.3f", sc_gini(motor$claims, m$fitted, motor$exposure)))
  gini <- sc_gini(motor$claims, m$fitted)
  expect_true(gini > 0 && gini < 1)
  expect_close(gini, g$glm$gini, 1e-8)
  expect_close(sc_gini(1:10, 1:10), 1 - 2 * sum(diff(cumsum(rep(0.1, 10))) * (cumsum(1:10)[-1] + cumsum(1:10)[-10]) / 55 / 2))
  expect_equal(nrow(sc_lift(motor$claims, m$fitted)), 10)
})

test_that("frequency × severity matches the golden table", {
  g <- golden()
  motor <- motor_data()
  fs <- sc_freq_sev(motor, "region", count = "claims", amount = "sev", exposure = "exposure")
  gf <- split_df(g$freq_sev)
  expect_equal(names(fs), names(gf))
  expect_equal(fs$region, gf$region)
  for (col in names(gf)[-1]) expect_close(fs[[col]], gf[[col]], 1e-8, label = col)
  tot <- fs[fs$region == "total", ]
  expect_true(abs(tot$claims - sum(motor$claims)) < 1e-9)
  expect_true(abs(tot$pure_premium - tot$frequency * tot$severity) < 1e-6)
  expect_equal(sc_title(fs), "Frequency × severity by region")
  expect_equal(sc_notes(fs), "frequency = claims / exposure; severity = amount / claims; pure premium = amount / exposure = frequency × severity.")
  one <- sc_freq_sev(motor, count = "claims", amount = "sev", exposure = "exposure")
  expect_equal(nrow(one), 1)
  expect_equal(names(one), c("exposure", "claims", "amount", "frequency", "severity", "pure_premium"))
  expect_close(one$claims, sum(motor$claims))
  expect_equal(sc_title(one), "Frequency × severity")
  # inferred columns ("claims" is a value alias, so a claim is a positive amount); two grouping keys; amount-only counts
  inf <- sc_freq_sev(data.frame(region = c("a", "a", "b"), claims = c(1, 0, 2), exposure = c(1, 1, 2)), "region")
  expect_equal(inf$claims, c(1, 1, 2))
  expect_equal(inf$amount, c(1, 2, 3))
  inf2 <- sc_freq_sev(data.frame(region = c("a", "a", "b"), claim_count = c(1, 0, 2), exposure = c(1, 1, 2)), "region")
  expect_equal(inf2$claims, c(1, 2, 3))
  expect_equal(inf2$frequency, c(0.5, 1, 0.75))
  two <- sc_freq_sev(motor, c("region", "y"), count = "claims", amount = "sev", exposure = "exposure")
  expect_equal(names(two)[1:2], c("region", "y"))
  expect_equal(nrow(two), 7)
  expect_equal(two$region[7], "total")
  expect_equal(two$y[7], "total")
  amt <- sc_freq_sev(data.frame(g = c("a", "a", "b"), amount = c(100, 0, 50)), "g")
  expect_equal(amt$claims, c(1, 1, 2))
  expect_equal(amt$severity, c(100, 50, 75))
  expect_error(sc_freq_sev(data.frame(g = c("a", "b"), x = 1:2), "g"), "need a claim count and/or amount column")
})

test_that("loss ratio and burning cost", {
  lr <- sc_loss_ratio(data.frame(paid = c(100, 50, 30), premium = c(200, 100, 100), line = c("a", "a", "b")), "line")
  expect_s3_class(lr, "scelo_table")
  expect_equal(names(lr), c("line", "loss", "premium", "loss_ratio"))
  expect_equal(lr$line, c("a", "b", "total"))
  expect_equal(lr$loss_ratio[lr$line == "total"], 0.45)
  expect_equal(lr$loss_ratio[lr$line == "a"], 0.5)
  expect_equal(sc_title(lr), "Loss ratio by line")
  all <- sc_loss_ratio(data.frame(paid = c(100, 50, 30), premium = c(200, 100, 100)))
  expect_equal(nrow(all), 1)
  expect_equal(all$loss_ratio, 0.45)
  expect_equal(sc_title(all), "Loss ratio")
  bc <- sc_burning_cost(data.frame(loss = c(100, 200), exposure = c(10, 10), year = c(2020, 2021)), trend = 0.1, years = "year", to_year = 2021)
  expect_true(abs(bc - (110 + 200) / 20) < 1e-9)
  expect_equal(sc_burning_cost(data.frame(loss = c(100, 200), exposure = c(10, 10))), 15)
  expect_equal(sc_burning_cost(data.frame(loss = c(100, 200), exposure = c(10, 10), year = c(2020, 2021)), trend = 0.1, years = "year"), (110 + 200) / 20)
})
