# Climate: ensembles, return periods, parametric triggers, AAL, anomalies
# (golden values from the Python package on the bundled climate sample).

test_that("ensemble summary matches the golden table", {
  g <- golden()
  cl <- sc_sample("climate")
  e <- sc_ensemble(cl, "t2m")
  expect_s3_class(e, "scelo_table")
  expect_equal(nrow(e), 30)
  expect_true(all(e$spread >= 0))
  ge <- split_df(g$ensemble_t2m)
  expect_equal(names(e), names(ge))
  expect_equal(e$date, ge$date)
  for (col in c("mean", "spread", "min", "max")) expect_close(e[[col]], ge[[col]], 1e-8, label = col)
  expect_equal(sc_title(e), "Ensemble · 3 members")
  expect_equal(sc_basis(e), "t2m_era5, t2m_merra2, t2m_jra3q")
  expect_equal(sc_notes(e), "Median member CV 0.016: the reanalyses agree closely on this variable.")
  pr <- sc_ensemble(cl, "pr")
  expect_equal(sc_basis(pr), "pr_era5, pr_merra2, pr_jra3q")
  expect_match(sc_notes(pr), "disagree materially|broadly agree")
  given <- sc_ensemble(cl, members = c("t2m_era5", "t2m_jra3q"))
  expect_equal(sc_title(given), "Ensemble · 2 members")
  expect_close(given$mean, (cl$t2m_era5 + cl$t2m_jra3q) / 2)
  nodate <- sc_ensemble(cl[-1], "t2m")
  expect_equal(names(nodate), c("mean", "spread", "min", "max"))
  holes <- cl
  holes$t2m_era5[1] <- NA
  h <- sc_ensemble(holes, "t2m")
  expect_close(h$mean[1], mean(c(cl$t2m_merra2[1], cl$t2m_jra3q[1])))
  expect_close(h$spread[1], stats::sd(c(cl$t2m_merra2[1], cl$t2m_jra3q[1])))
  expect_error(sc_ensemble(cl, "wind"), "no reanalysis member columns found")
})

test_that("return periods match the golden table", {
  g <- golden()
  rp <- sc_return_period(g$return_period$x)
  expect_s3_class(rp, "scelo_table")
  gt <- split_df(g$return_period$table)
  expect_equal(names(rp), c("return_period", "empirical", "gumbel"))
  expect_equal(rp$return_period, gt$return_period)
  expect_close(rp$empirical, gt$empirical, 1e-8)
  expect_close(rp$gumbel, gt$gumbel, 1e-8)
  expect_true(all(diff(rp$gumbel) > 0))
  expect_true(is.na(rp$empirical[nrow(rp)]))
  expect_equal(sc_basis(rp), "40 values over 40 years")
  ev <- sc_return_period(g$return_period$x, years = 100)
  expect_true(all(is.na(ev$gumbel)))
  expect_equal(sc_basis(ev), "40 values over 100 years")
  expect_close(ev$empirical[ev$return_period == 101], max(g$return_period$x))
  expect_true(all(!is.na(ev$empirical[ev$return_period <= 100])))
  expect_equal(nrow(sc_return_period(1:10, periods = c(2, 5))), 2)
})

test_that("parametric trigger, AAL and anomalies", {
  g <- golden()
  tr <- sc_parametric_trigger(1:100)
  expect_equal(tr, list(trigger = 91, cap = 364, attachment_probability = 0.1))
  expect_equal(tr$trigger, g$parametric_trigger$trigger)
  expect_equal(tr$cap, g$parametric_trigger$cap)
  expect_equal(tr$attachment_probability, g$parametric_trigger$attachment_probability)
  expect_equal(sc_parametric_trigger(c(5, NA, 1, 3), p = 0.5, cap_multiple = 2)$trigger, 3)
  expect_error(sc_parametric_trigger(numeric()), "no losses")
  expect_equal(sc_aal(c(10, 20, 30), years = 3), 20)
  expect_equal(sc_aal(c(1e6, 5e6), frequencies = c(0.1, 0.01)), 150000)
  expect_error(sc_aal(c(10, 20)), "give frequencies per event or the number of years of record")
  idx <- seq(as.Date("2020-01-01"), by = "month", length.out = 24)
  an <- sc_anomaly(stats::setNames(rep(0:11, 2), idx))
  expect_true(all(abs(an) < 1e-12))
  expect_equal(names(an), as.character(idx))
  an2 <- sc_anomaly(rep(0:11, 2), dates = idx, baseline = rep(1, 12), baseline_dates = idx[1:12])
  expect_equal(unname(an2), rep(0:11, 2) - 1)
  cl <- sc_sample("climate")
  d <- sc_anomaly(cl[c("date", "t2m_era5")])
  expect_close(unname(d), cl$t2m_era5 - mean(cl$t2m_era5))
  daily <- sc_anomaly(stats::setNames(cl$t2m_era5, cl$date), by = "day")
  expect_true(all(abs(daily) < 1e-12))
  expect_error(sc_anomaly(1:3), "series needs dates")
})
