// AI model picker for the Tools workstation. Same pattern as
// SmartColumnDashboard: prompt the orchestrator with the dataset shape,
// parse JSON, fall back to a local heuristic if anything goes wrong.

import { streamOrchestrator } from "@/lib/api";
import type { ColumnMeta, Dataset } from "./SoftDataWorkstation";
import { type CatalogModel, MODEL_BY_ID, MODEL_CATALOG, type ModelFamily } from "./modelCatalog";

export type PickResult = {
  domain: ModelFamily;
  selected: Array<{ id: string; rationale: string }>;
  summary: string;
};

// ── data-shape signature ─────────────────────────────────────────────────────

export type DataSignature = {
  columnNames: string[];
  hasOriginYear: boolean;
  hasDevPeriod: boolean;
  hasPaid: boolean;
  hasIncurred: boolean;
  hasAge: boolean;
  hasSex: boolean;
  hasDeaths: boolean;
  hasExposure: boolean;
  hasGeographic: boolean;
  hasClaims: boolean;
  // Policy/quote-level pricing signals. Real-world rating headers rarely
  // say `paid` or `claims` verbatim: `hasClaimsCount` is the loose count
  // match (past_claims, claim_count, no_claims…) while `hasClaimsAmount`
  // is the monetary flavour (claim_amt, loss_cost, paid/incurred) — a
  // severity model is only sensible when a monetary column exists, a bare
  // claims COUNT can't feed it. `hasSumInsured` matches the `sum_insur*`
  // prefix so the common `sum_insurd` misspelling still hits; sum_assured
  // stays a life signal and is deliberately excluded here.
  hasClaimsCount: boolean;
  hasClaimsAmount: boolean;
  hasSumInsured: boolean;
  hasExcess: boolean;
  hasPremium: boolean;
  // Climate / weather / reanalysis signals. `hasReanalysis` is the strongest
  // — columns named like `t2m_era5`, `tp_merra2`, `wind_jra3q` are almost
  // certainly from one of the canonical reanalyses and the user is doing
  // climate-actuarial work (parametric design, CLIMADA, etc).
  hasTemperature: boolean;
  hasPrecipitation: boolean;
  hasWind: boolean;
  hasReanalysis: boolean;
  hasDateColumn: boolean;
  // Lifelib / life-insurance model-point signals. The hard tell is the
  // simultaneous presence of `age_at_entry`, `sum_assured`, and `policy_term`
  // — that triplet is lifelib's canonical MP shape and almost never appears
  // outside life-projection work. Weaker signals (account_value, csm,
  // policy_id-only) trigger the family but with lower confidence routing.
  hasAgeAtEntry: boolean;
  hasSumAssured: boolean;
  hasPolicyTerm: boolean;
  hasPolicyId: boolean;
  hasAccountValue: boolean;
  hasDurationMth: boolean;
  // WMTR forecast signals. The hard tell is the simultaneous presence of
  // alpha_m, alpha_t, and alpha_r — the Cobb-Douglas exponent triplet. A
  // shock-severity column tightens the signal further.
  hasAlphaTriplet: boolean;
  hasShockColumn: boolean;
  hasWmtrWeights: boolean;
  /** Swarm-simulation output dataset — columns prefixed with `sim_` are
   *  the unambiguous tell. Generated by the swarms server's
   *  /api/simulate endpoint (per-agent outcome rows + demographics).
   *  These don't fit any actuarial model family directly; the row IS
   *  the simulation result. Route to descriptive stats. */
  hasSimulationOutcomes: boolean;
  numNumeric: number;
  numCategorical: number;
  rowCount: number;
};

// `searchAny` checks whether *any* column matches — `cols.some(pattern.test)`
// allows partial matches (e.g. `t2m_era5` matches /(^|_)(t2m|temp|tas)(_|$)/).
const nameMatches = (cols: string[], pattern: RegExp) =>
  cols.some((c) => pattern.test(c.toLowerCase()));

export function dataSignature(dataset: Dataset, metas: ColumnMeta[]): DataSignature {
  const lower = dataset.columns.map((c) => c.toLowerCase());
  return {
    columnNames: dataset.columns,
    hasOriginYear: nameMatches(lower, /^(origin|accident|underwriting|policy)_?year$/),
    hasDevPeriod: nameMatches(lower, /^(dev|development)_?(period|year)?$/),
    hasPaid: nameMatches(lower, /^paid$/),
    hasIncurred: nameMatches(lower, /^incurred$/),
    hasAge: nameMatches(lower, /^age$/),
    hasSex: nameMatches(lower, /^(sex|gender)$/),
    hasDeaths: nameMatches(lower, /^(deaths?|q_?x|mortality)$/),
    hasExposure: nameMatches(lower, /^(exposure|e_?x|lives|policy_years)$/),
    hasGeographic: nameMatches(lower, /^(state|province|country|region|county|city)$/),
    hasClaims: nameMatches(lower, /^(claim|claims|claim_amt|claim_count|frequency|severity)$/),
    hasClaimsCount: nameMatches(lower, /(^|_)claims?(_count|_cnt)?(_|$)/),
    hasClaimsAmount:
      nameMatches(lower, /(^|_)(claims?|loss)_?(amt|amount|paid|cost|incurred)(_|$)/) ||
      nameMatches(lower, /^severity$/),
    hasSumInsured: nameMatches(lower, /^sum_insur|^tiv$/),
    hasExcess: nameMatches(lower, /^(excess|deductible)$/),
    hasPremium: nameMatches(lower, /(^|_)premium/),
    // Weather variables — partial match anywhere in the column name so
    // `t2m_era5`, `mean_t2m`, `tas_max` all hit.
    hasTemperature: nameMatches(lower, /(^|_)(t2m|temp|temperature|tas|tmax|tmin|tavg)(_|$)/),
    hasPrecipitation: nameMatches(
      lower,
      /(^|_)(pr|precip|precipitation|rain|rainfall|tp|tprecip)(_|$)/,
    ),
    hasWind: nameMatches(lower, /(^|_)(wind|wspd|u10|v10|gust|sfcwind)(_|$)/),
    // Reanalysis suffixes (era5 / era5_land / merra2 / merra-2 / jra3q / jra-3q
    // / ncep / cfsr / nora). Strongest single climate signal.
    hasReanalysis: nameMatches(lower, /(era5|merra[-_]?2|jra[-_]?3?q?|ncep|cfsr|nora)/),
    // Real headers are usually suffixed (policy_start_date, dob, lic_date)
    // rather than a bare `date`, so match on the suffix — plus whatever
    // summarise already typed as a date column.
    hasDateColumn:
      nameMatches(lower, /(^|_)(date|day|time|datetime|timestamp|dob)$/) ||
      metas.some((m) => m.type === "date"),
    // Lifelib MP signals.
    hasAgeAtEntry: nameMatches(lower, /^(age_at_entry|ageatentry|issue_age)$/),
    hasSumAssured: nameMatches(lower, /^(sum_assured|sumassured|face_amount|face|sa|sum_insured)$/),
    hasPolicyTerm: nameMatches(lower, /^(policy_term|policyterm|term_years|term)$/),
    hasPolicyId: nameMatches(lower, /^(policy_id|policyid|model_point_id|mp_id)$/),
    hasAccountValue: nameMatches(lower, /^(account_value|av|cash_value|csv)$/),
    hasDurationMth: nameMatches(lower, /^(duration_mth|durationmth|duration_months|elapsed_mth)$/),
    // WMTR forecast signals.
    hasAlphaTriplet:
      nameMatches(lower, /^(alpha_m|alpham)$/) &&
      nameMatches(lower, /^(alpha_t|alphat)$/) &&
      nameMatches(lower, /^(alpha_r|alphar)$/),
    hasShockColumn: nameMatches(lower, /^(shock|shock_severity|severity)$/),
    hasWmtrWeights:
      nameMatches(lower, /^(w_f|wf)$/) ||
      nameMatches(lower, /^(w_rel|wrel)$/) ||
      nameMatches(lower, /^(w_s|ws)$/),
    hasSimulationOutcomes: lower.some((c) => c.startsWith("sim_")),
    numNumeric: metas.filter((m) => m.type === "number").length,
    numCategorical: metas.filter((m) => m.type === "string").length,
    rowCount: dataset.rows.length,
  };
}

// ── heuristic fallback ──────────────────────────────────────────────────────

// `variant` is the regenerate counter: 0 returns the canonical pick,
// higher values rotate deterministic same-family alternates in (see
// rotateAlternates) so an offline regenerate isn't a silent no-op loop
// returning the identical list forever.
export function heuristicPick(sig: DataSignature, variant = 0): PickResult {
  const base = basePick(sig);
  return variant > 0 ? rotateAlternates(base, variant) : base;
}

function basePick(sig: DataSignature): PickResult {
  // Swarm-simulation output → general / descriptive. The row IS the
  // simulation result; trying to fit a reserving / pricing / mortality
  // model to it would be a category error (and trigger the "triangle
  // not detected" / "no claims" runner errors the user just hit). Lead
  // with descriptive so the per-row sim_* columns get summarised; pair
  // with GBM (LightGBM) so the user can probe drivers across sim_*
  // outcomes if they want.
  if (sig.hasSimulationOutcomes) {
    return {
      domain: "general",
      selected: [
        {
          id: "descriptive",
          rationale:
            "Simulation output: descriptive stats summarise the sim_* outcome columns across the population.",
        },
        {
          id: "gbm",
          rationale:
            "Optional driver probe — GBM on sim_* outcomes vs demographics to expose which profile features dominate the response.",
        },
        {
          id: "shap",
          rationale:
            "Per-row attribution for the GBM — which profile features pulled which agents into which outcome bucket.",
        },
      ],
      summary:
        "Swarm-simulation rows (sim_* outcome columns). Descriptive headline, optional GBM + SHAP probe for outcome drivers.",
    };
  }
  // WMTR forecast shape → forecast family. Strongest tell is the
  // (alpha_m, alpha_t, alpha_r) triplet. A shock column or any w_*
  // weight cinches it. Routes BEFORE life so a parameter table for
  // life-flavoured WMTR sits with the right family.
  if (sig.hasAlphaTriplet) {
    return {
      domain: "forecast",
      selected: [
        {
          id: "wmtr-projection",
          rationale:
            "α_M / α_T / α_R triplet detected — runs the W(M,T,R) Monte Carlo survival projection directly.",
        },
        {
          id: "wmtr-sensitivity",
          rationale:
            "Sweep shock severity (mild / moderate / severe) on the same config to size the stress sensitivity.",
        },
      ],
      summary:
        "WMTR forecast parameters: project survival under shocks + sweep the shock dial for sensitivity.",
    };
  }
  // Lifelib model-point shape → life family. Strong tell is the triplet
  // (age_at_entry · sum_assured · policy_term). If the file also carries
  // an account_value column, prefer CashValue / savings; otherwise lead
  // with BasicTerm. Either way the IFRS17 / Solvency II / cluster nodes
  // come along because they consume the same MP file downstream.
  if (sig.hasAgeAtEntry && sig.hasSumAssured && sig.hasPolicyTerm) {
    const isSavings = sig.hasAccountValue;
    const headline = isSavings ? "cashvalue-savings" : "basicterm-projection";
    const headlineWhy = isSavings
      ? "MP carries account_value — UL / savings shape, projects via CashValue_ME."
      : "MP triplet (age_at_entry · sum_assured · policy_term) — runs lifelib BasicTerm_M in-browser.";
    return {
      domain: "life",
      selected: [
        { id: headline, rationale: headlineWhy },
        {
          id: "ifrs17-csm",
          rationale:
            "Same MP file feeds the IFRS 17 LRC / LIC / CSM roll-forward (lifelib ifrs17sim).",
        },
        {
          id: "solvency2-life",
          rationale:
            "Standard-formula life SCR (mortality / longevity / lapse / expense / CAT) on the same MPs.",
        },
        {
          id: "cluster-modelpoints",
          rationale:
            "If the MP file scales past 10k, compress with lifelib cluster before nested runs.",
        },
      ],
      summary: isSavings
        ? "Lifelib MP file with account-value (UL / savings): CashValue_ME for the headline, IFRS 17 CSM + Solvency II life SCR alongside, cluster for compression."
        : "Lifelib MP file (term life): BasicTerm_M for the headline projection, IFRS 17 CSM + Solvency II life SCR alongside, cluster for compression at scale.",
    };
  }
  // Claims-triangle shape → reserving family.
  if (sig.hasOriginYear && sig.hasDevPeriod && (sig.hasPaid || sig.hasIncurred)) {
    return {
      domain: "reserving",
      selected: [
        {
          id: "chain-ladder",
          rationale: "Triangle shape detected — chain ladder is the workhorse.",
        },
        { id: "mack", rationale: "Adds variance bounds around the chain-ladder reserve estimate." },
        {
          id: "bornhuetter-ferguson",
          rationale:
            "Useful when later development periods are sparse — borrows from a prior loss ratio.",
        },
        {
          id: "bootstrap-ibnr",
          rationale: "Full predictive distribution via residual resampling.",
        },
      ],
      summary:
        "Triangle-shaped reserving data: chain-ladder + Mack for point + variance, BF for sparsity, bootstrap for the full distribution.",
    };
  }
  // Mortality-table shape → mortality family.
  if (sig.hasAge && (sig.hasDeaths || sig.hasExposure)) {
    return {
      domain: "mortality",
      selected: [
        { id: "lee-carter", rationale: "Age × time mortality data — classic Lee-Carter target." },
        { id: "cbd", rationale: "Old-age fit; useful contrast with Lee-Carter." },
        {
          id: "lifecontingencies",
          rationale: "Once you have a life table, you can price annuities and assurances.",
        },
      ],
      summary:
        "Mortality data with age and deaths/exposure: Lee-Carter + CBD for projection, life contingencies for downstream pricing.",
    };
  }
  // Claims / policy-level pricing shape → pricing family. Two routes in:
  // a claims signal (paid amounts or a past-claims count) with a couple of
  // categorical rating factors, or a rating-factor-heavy schema (sum
  // insured / excess / premium + 3 or more categoricals) even before any
  // claims column. Both must be non-triangle. glm-severity only joins
  // when a monetary claims column exists — a count like past_claims can't
  // feed a severity model.
  const hasClaimsSignal = (sig.hasClaimsCount || sig.hasPaid) && sig.numCategorical >= 2;
  const hasRatingFactors =
    (sig.hasSumInsured || sig.hasExcess || sig.hasPremium) && sig.numCategorical >= 3;
  if ((hasClaimsSignal || hasRatingFactors) && !sig.hasDevPeriod) {
    const hasMonetaryClaims = sig.hasPaid || sig.hasIncurred || sig.hasClaimsAmount;
    return {
      domain: "pricing",
      selected: [
        {
          id: "glm-frequency",
          rationale: "Categorical rating factors + claims signal → Poisson GLM frequency.",
        },
        ...(hasMonetaryClaims
          ? [
              {
                id: "glm-severity",
                rationale:
                  "Monetary claims column present — severity alongside frequency for a full pure premium.",
              },
            ]
          : []),
        { id: "gbm", rationale: "Nonlinear interactions — GBM picks them up where GLM struggles." },
        { id: "shap", rationale: "Explainability for the GBM in pricing meetings." },
      ],
      summary: hasMonetaryClaims
        ? "Claims-level pricing data with covariates: frequency × severity GLMs plus a GBM for nonlinearities, explained via SHAP."
        : "Policy-level rating data (claim counts, no monetary claims column): frequency GLM plus a GBM for nonlinearities, explained via SHAP.",
    };
  }
  // Weather / climate-reanalysis shape → climate / cat. Strongest signal is
  // a reanalysis suffix (era5 / merra2 / jra3q) or a clear temperature /
  // precipitation / wind variable on a date-indexed dataset. Two-of-three
  // weather signals or any reanalysis suffix is enough — we'd rather
  // surface CLIMADA + parametric to a user with weather columns than
  // bounce them to descriptive stats.
  const weatherSignals =
    (sig.hasTemperature ? 1 : 0) + (sig.hasPrecipitation ? 1 : 0) + (sig.hasWind ? 1 : 0);
  if ((sig.hasReanalysis || weatherSignals >= 2) && sig.rowCount > 0) {
    const cues: string[] = [];
    if (sig.hasReanalysis) cues.push("reanalysis-tagged columns");
    if (sig.hasTemperature) cues.push("temperature");
    if (sig.hasPrecipitation) cues.push("precipitation");
    if (sig.hasWind) cues.push("wind");
    if (sig.hasDateColumn) cues.push("date-indexed");
    return {
      domain: "climate",
      selected: [
        {
          id: "climada",
          rationale: `${cues.join(" + ")} — fits CLIMADA hazard / exposure / vulnerability stack.`,
        },
        {
          id: "parametric-design",
          rationale:
            "Daily weather time-series is the canonical input for parametric trigger calibration.",
        },
        {
          id: "descriptive",
          rationale: "Headline summary of the variable distributions before pricing the trigger.",
        },
      ],
      summary:
        "Climate / reanalysis time-series: CLIMADA hazard machinery + parametric design with a descriptive baseline.",
    };
  }
  // Geographic-only shape (province / city codes, no weather variables) →
  // also climate-family but framed as exposure / cat work rather than the
  // reanalysis-driven workflow. Only when the schema actually looks
  // hazard/exposure-shaped: a geo column among FEW other covariates, or an
  // explicit exposure column. A geo code buried in a wide table of policy
  // rating factors (province on a motor book) is a pricing covariate, not
  // a climate signal — fall through to the general fallback instead.
  const geoHazardShaped = sig.columnNames.length <= 6 || weatherSignals >= 1 || sig.hasExposure;
  if (sig.hasGeographic && geoHazardShaped && sig.rowCount > 0) {
    return {
      domain: "climate",
      selected: [
        { id: "climada", rationale: "Geographic column suggests hazard / exposure modelling." },
        {
          id: "parametric-design",
          rationale: "Trigger-based design once hazard footprints are clear.",
        },
        { id: "descriptive", rationale: "Summary baseline before the heavier cat machinery." },
      ],
      summary:
        "Geographic / exposure-shaped data: CLIMADA + parametric design with a descriptive baseline.",
    };
  }
  // Fallback — descriptive only with a couple of general companions.
  return {
    domain: "general",
    selected: [
      { id: "descriptive", rationale: "Headline summary while we figure out the right family." },
      { id: "glm-frequency", rationale: "Generic candidate if claim-like signal emerges." },
      { id: "gbm", rationale: "Generic nonlinear baseline for any tabular regression." },
    ],
    summary:
      "No strong domain signal detected — descriptive stats plus generic GLM/GBM candidates.",
  };
}

// Deterministic same-family rotation for regenerate. Each variant swaps
// exactly ONE pick for a catalog model from the same family that isn't
// already selected, cycling through every (slot × alternate) pair so
// successive regenerates keep producing a different — but reproducible —
// mix. Families with no unpicked alternates (e.g. all four reserving
// models already on a triangle pick) leave the pick unchanged.
function rotateAlternates(base: PickResult, variant: number): PickResult {
  const picked = new Set(base.selected.map((s) => s.id));
  const swaps: Array<{ slot: number; alt: CatalogModel }> = [];
  base.selected.forEach((s, slot) => {
    const family = MODEL_BY_ID.get(s.id)?.family;
    if (!family) return;
    for (const m of MODEL_CATALOG) {
      if (m.family === family && !picked.has(m.id)) swaps.push({ slot, alt: m });
    }
  });
  if (swaps.length === 0) return base;
  const { slot, alt } = swaps[(variant - 1) % swaps.length];
  const selected = base.selected.map((s, i) =>
    i === slot
      ? { id: alt.id, rationale: `Regenerated alternate (${alt.family}): ${alt.description}` }
      : s,
  );
  return { ...base, selected };
}

// ── LLM picker ──────────────────────────────────────────────────────────────

function describeColumnsForPrompt(metas: ColumnMeta[]): string {
  return metas
    .map((m) => {
      if (m.type === "number") {
        const range =
          m.min !== undefined && m.max !== undefined ? `, range=[${m.min}, ${m.max}]` : "";
        return `  • ${m.name} (num, ${m.unique} unique${range})`;
      }
      const top =
        m.topValues
          ?.slice(0, 4)
          .map((v) => v.value)
          .join(", ") ?? "";
      return `  • ${m.name} (cat, ${m.unique} unique${top ? `, top: ${top}` : ""})`;
    })
    .join("\n");
}

function buildPickerPrompt(args: {
  dataset: Dataset;
  metas: ColumnMeta[];
  variant: number;
  previousIds: string[];
}): string {
  const { dataset, metas, variant, previousIds } = args;
  const catalogLines = MODEL_CATALOG.map(
    (m) => `- "${m.id}" | ${m.family} | ${m.description}`,
  ).join("\n");

  const variantNudge =
    variant > 0
      ? `\nREGENERATION attempt #${variant + 1}. Previous selection was: [${previousIds.join(", ")}]. Pick a meaningfully different mix this time — change at least one id, ideally several.`
      : "";

  return `CRITICAL: DO NOT CALL ANY TOOL. DO NOT dispatch documentation.predict, reserving.predict, or any specialist. This is a pure JSON-generation task answered as a chat reply.

Task: given a dataset shape, recommend 3-6 actuarial / statistical models from the FIXED catalog below. Return JSON only.

DATASET
name: ${dataset.name}
rows: ${dataset.rows.length}
columns:
${describeColumnsForPrompt(metas)}

CATALOG (id | family | description) — pick ids ONLY from this list:
${catalogLines}

RULES
- Pick 3 to 6 models that fit this data shape.
- Prefer one dominant family (e.g. reserving) and optionally 1-2 models from related families.
- Use ids EXACTLY as written above; do not invent new ids.
- Each model gets a short, data-grounded rationale (≤ 18 words).
- Output JSON only — no prose, no code fences, no tool calls.

FAMILY ROUTING (use as a strong prior — override only with explicit data evidence):
- SWARM-SIMULATION OUTPUT (any column starting with \`sim_\`, e.g. sim_workdays_lost, sim_treatment_uptake, sim_mortality_probability) → \`general\`: descriptive (lead), gbm + shap (optional driver probes on the sim_* outcomes vs demographic profile). NEVER pick reserving / pricing / mortality on these — the row IS the simulation result, not raw experience data; reserving's triangle assumptions will silently fail.
- LIFELIB MODEL POINTS (age_at_entry + sum_assured + policy_term, optionally with sex / duration_mth / premium_pp / account_value) → \`life\`: basicterm-projection (default headline) OR cashvalue-savings (if account_value present), plus ifrs17-csm + solvency2-life + cluster-modelpoints. THIS IS A STRONG SIGNAL; the user has a life-insurance model-point file and the right family is life — not mortality (which is for fitting tables), not pricing (which is for P&C covariates).
- Triangle shape (origin_year + dev_period + paid/incurred) → \`reserving\`: chain-ladder, mack, bornhuetter-ferguson, bootstrap-ibnr.
- Age × time with deaths or exposure (no sum_assured / policy_term) → \`mortality\`: lee-carter, cbd, lifecontingencies.
- Claims-level with covariates (no triangle) → \`pricing\`: glm-frequency, glm-severity, gbm, shap.
- POLICY / QUOTE-LEVEL RATING DATA — one row per policy or quote: a unique id, vehicle / driver / property rating factors (make, gears, marital status, gender, licence / policy dates), sum-insured or excess / deductible, past_claims or prior-insurance flags → \`pricing\`: glm-frequency, gbm, shap. Add glm-severity ONLY when a monetary claim-amount column exists — a past-claims COUNT alone cannot feed a severity model. A province / region column here is a rating factor, NOT a climate signal.
- WEATHER / CLIMATE columns — names containing t2m, temp, temperature, tas, tp, precip, precipitation, rain, wind, u10, v10 — or REANALYSIS suffixes (era5, era5_land, merra2, merra-2, jra3q, jra-3q, ncep) → \`climate\`: climada, parametric-design, descriptive. THIS IS A STRONG SIGNAL; the user is doing climate-actuarial work and the right family is climate even if no geographic column exists.
- Date-indexed numeric time-series with no claims/triangle signal but multiple correlated numeric series → still consider \`climate\` if the column names look weather-flavoured.
- Geographic codes (state, province, country, region) but no weather columns → \`climate\` framed as exposure / cat work ONLY when geo + hazard / exposure columns dominate the schema and there are no policy-level covariates. If the geo code sits among policy rating factors, route to \`pricing\` instead.
- Yield-curve / rates columns or zero/forward curve data with no MP file → \`life\`: smithwilson-curve, economic-curves.
- Otherwise → \`general\`: descriptive plus a couple of generic candidates.${variantNudge}

OUTPUT SCHEMA:
{
  "domain": "reserving|mortality|pricing|climate|capital|pensions|life|general",
  "selected": [
    {"id": "<catalog id>", "rationale": "<≤ 18 words>"}
  ],
  "summary": "<one sentence describing why this mix fits>"
}`;
}

function extractFirstJson(text: string): unknown | null {
  const trimmed = text.trim();
  if (trimmed.length === 0) return null;
  try {
    return JSON.parse(trimmed);
  } catch {
    /* fall through */
  }
  const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) {
    try {
      return JSON.parse(fenced[1].trim());
    } catch {
      /* fall through */
    }
  }
  const block = trimmed.match(/\{[\s\S]*\}/);
  if (block) {
    try {
      return JSON.parse(block[0]);
    } catch {
      /* fall through */
    }
  }
  return null;
}

const VALID_FAMILIES: ReadonlySet<ModelFamily> = new Set([
  "reserving",
  "mortality",
  "pricing",
  "climate",
  "capital",
  "pensions",
  "life",
  "forecast",
  "general",
]);

function coercePickResult(raw: unknown): PickResult | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as { domain?: unknown; selected?: unknown; summary?: unknown };
  if (typeof r.domain !== "string" || !VALID_FAMILIES.has(r.domain as ModelFamily)) {
    return null;
  }
  if (!Array.isArray(r.selected)) return null;
  const selected: Array<{ id: string; rationale: string }> = [];
  for (const item of r.selected) {
    if (!item || typeof item !== "object") continue;
    const it = item as { id?: unknown; rationale?: unknown };
    if (typeof it.id !== "string") continue;
    const model = MODEL_BY_ID.get(it.id);
    if (!model) continue; // ignore invented ids
    selected.push({
      id: it.id,
      rationale: typeof it.rationale === "string" ? it.rationale : model.description,
    });
    if (selected.length >= 6) break;
  }
  if (selected.length === 0) return null;
  return {
    domain: r.domain as ModelFamily,
    selected,
    summary: typeof r.summary === "string" ? r.summary : "",
  };
}

// Strong-signal short-circuit. When the dataset shape is unambiguous —
// the lifelib MP triplet, a real claims triangle, or a weather reanalysis
// ensemble — the heuristic IS the right answer and the LLM call adds
// nothing but latency + drift risk. The user reported the LLM mis-routing
// a lifelib MP file to reserving models; this preempts that class of bug.
//
// Returns the heuristic pick when the signature has a strong match, or
// null when the shape is ambiguous and the LLM should be consulted.
// `variant` (the regenerate counter) flows through to heuristicPick so an
// explicit regenerate on a short-circuited shape still rotates same-family
// alternates instead of silently returning the identical list.
function strongSignalPick(sig: DataSignature, variant: number): PickResult | null {
  const isSimulationOutput = sig.hasSimulationOutcomes;
  const isWmtrParams = sig.hasAlphaTriplet;
  const isLifelibMp = sig.hasAgeAtEntry && sig.hasSumAssured && sig.hasPolicyTerm;
  const isClaimsTriangle =
    sig.hasOriginYear && sig.hasDevPeriod && (sig.hasPaid || sig.hasIncurred);
  const weatherSignals =
    (sig.hasTemperature ? 1 : 0) + (sig.hasPrecipitation ? 1 : 0) + (sig.hasWind ? 1 : 0);
  const isWeatherReanalysis = sig.hasReanalysis || weatherSignals >= 2;
  if (
    isSimulationOutput ||
    isWmtrParams ||
    isLifelibMp ||
    isClaimsTriangle ||
    isWeatherReanalysis
  ) {
    return heuristicPick(sig, variant);
  }
  return null;
}

export async function fetchModelPicks(args: {
  dataset: Dataset;
  metas: ColumnMeta[];
  variant: number;
  previousIds: string[];
  signal: AbortSignal;
}): Promise<PickResult> {
  // Short-circuit on strong signatures so the routing is deterministic and
  // the LLM never has the chance to ignore the family-routing prompt.
  const sig = dataSignature(args.dataset, args.metas);
  const strong = strongSignalPick(sig, args.variant);
  if (strong) return strong;

  const prompt = buildPickerPrompt(args);
  let buffer = "";
  let streamError: string | null = null;
  await streamOrchestrator(
    prompt,
    [],
    {
      onEvent: (e) => {
        if (e.kind === "message") buffer += e.payload.text;
        else if (e.kind === "error") streamError = e.payload.message;
      },
      onError: (e) => {
        streamError = e.message;
      },
    },
    { signal: args.signal },
  );
  if (args.signal.aborted) throw new Error("aborted");
  if (streamError) throw new Error(streamError);
  const parsed = extractFirstJson(buffer);
  const coerced = coercePickResult(parsed);
  if (!coerced) throw new Error("could not parse a model pick from the model reply");
  return coerced;
}

// Re-export so callers don't need two imports
export type { CatalogModel } from "./modelCatalog";
